#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ytrie.h"

void delete_using_prefix(ytrie *trie, char *prefix)
{
    ylist *list;
    int len = strlen(prefix);
    list = ytrie_search_range(trie, prefix, len);
    if(!list)
        return;
    while(!ylist_empty(list))
    {
        char *cb_key = ylist_pop_front(list);
        printf("%s %s\n", "[PREFIX_DELETE]", cb_key);
        ytrie_delete(trie, cb_key, strlen(cb_key));
        free(cb_key);
    }
    ylist_destroy(list);
}

int main(int argc, char *argv[])
{
	if(argc > 1)
	{
		char *deleted;
		char buf[512], *line;
		FILE *fp = fopen(argv[1], "r");
		if(!fp)
		{
			printf("[EXIT] no argument\n");
			return -1;
		}
		
		printf("CREATE\n");
		ytrie *trie = ytrie_create();
		while((line = fgets(buf, 512, fp)) != NULL)
		{
			char *copy = strdup(line);
			char *newline = strchr(copy, '\n');
			if(newline)
				*newline=0;
			
			char *old = ytrie_insert(trie, copy, strlen(copy), copy);
			if(old)
			{
				printf("[DUPLICATED INSERT] %s\n", old);
				free(old);
			}
			else
			{
				printf("[INSERT] %s\n", copy);
			}
		}
      	
		// SIZE
		printf("[SIZE] %lu\n\n", ytrie_size(trie));

		int i;
		// int matchlen = 0;
		char *item[] = {
"ietf-interfaces/interfaces",
"ietf-interfaces/interfaces/interface",
"ietf-interfaces/interfaces/interface/name",
"ietf-interfaces/interfaces/interface/description",
"ietf-interfaces/interfaces/interface/type",
"ietf-interfaces/interfaces/interface/enabled",
"ietf-ip/interfaces/interface/ipv4",
"ietf-ip/interfaces/interface/ipv4/enabled",
"ietf-ip/interfaces/interface/ipv4/forwarding",
"ietf-ip/interfaces/interface/ipv4/address",
"ietf-ip/interfaces/interface/ipv4/address/ip",
"ietf-ip/interfaces/interface/ipv4/address/subnet",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/netmask",
"hfr-base-spec/interfaces/interface/ipv4/address/secondary",
"ieee802-ethernet-interface/interfaces/interface/ethernet",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation/enable",
"ieee802-ethernet-interface/interfaces/interface/ethernet/duplex",
"ieee802-ethernet-interface/interfaces/interface/ethernet/speed",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause/direction",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/force-flow-control",
"bbf-fastdsl/interfaces/interface/line",
"bbf-fastdsl/interfaces/interface/line/configured-mode",
"bbf-fast/interfaces/interface/line/line",
"bbf-fast/interfaces/interface/line/line/profile-config",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode/line-config-vector",
"bbf-fast/interfaces/interface/line/line/threshold-template",
"bbf-fast/interfaces/interface/line/line/test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/rtx-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/tps-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/dra-test-mode",
"bbf-fast/interfaces/interface/line/line/update-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o/update-ne-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r/update-fe-test",
"bbf-fast/interfaces/interface/line/line/read-test",
"bbf-fast/interfaces/interface/line/line/read-test/downstream",
"bbf-fast/interfaces/interface/line/line/read-test/downstream/xlog-disturber-vce-port-index",
"bbf-fast/interfaces/interface/line/line/link-state",
"bbf-fast/interfaces/interface/line/line/link-state/link-state-forced",
"ietf-interfaces/interfaces",
"ietf-interfaces/interfaces/interface",
"ietf-interfaces/interfaces/interface/name",
"ietf-interfaces/interfaces/interface/description",
"ietf-interfaces/interfaces/interface/type",
"ietf-interfaces/interfaces/interface/enabled",
"ietf-ip/interfaces/interface/ipv4",
"ietf-ip/interfaces/interface/ipv4/enabled",
"ietf-ip/interfaces/interface/ipv4/forwarding",
"ietf-ip/interfaces/interface/ipv4/address",
"ietf-ip/interfaces/interface/ipv4/address/ip",
"ietf-ip/interfaces/interface/ipv4/address/subnet",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/netmask",
"hfr-base-spec/interfaces/interface/ipv4/address/secondary",
"ieee802-ethernet-interface/interfaces/interface/ethernet",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation/enable",
"ieee802-ethernet-interface/interfaces/interface/ethernet/duplex",
"ieee802-ethernet-interface/interfaces/interface/ethernet/speed",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause/direction",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/force-flow-control",
"bbf-fastdsl/interfaces/interface/line",
"bbf-fastdsl/interfaces/interface/line/configured-mode",
"bbf-fast/interfaces/interface/line/line",
"bbf-fast/interfaces/interface/line/line/profile-config",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode/line-config-vector",
"bbf-fast/interfaces/interface/line/line/threshold-template",
"bbf-fast/interfaces/interface/line/line/test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/rtx-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/tps-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/dra-test-mode",
"bbf-fast/interfaces/interface/line/line/update-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o/update-ne-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r/update-fe-test",
"bbf-fast/interfaces/interface/line/line/read-test",
"bbf-fast/interfaces/interface/line/line/read-test/downstream",
"bbf-fast/interfaces/interface/line/line/read-test/downstream/xlog-disturber-vce-port-index",
"bbf-fast/interfaces/interface/line/line/link-state",
"bbf-fast/interfaces/interface/line/line/link-state/link-state-forced",
		};
		for(i=0; i < (sizeof(item)/sizeof(char *)); i++)
		{
			deleted = ytrie_delete(trie, item[i], strlen(item[i]));
			if(deleted) {
				printf("[DELETE] %s (%ld)\n", item[i], strlen(item[i]));
				free(deleted);
			}
			else {
				printf("[XXX] %s (%ld)\n", item[i], strlen(item[i]));
			}
		}

		delete_using_prefix(trie, "ietf-ip");

		char *item2[] = {
"ietf-interfaces/interfaces",
"ietf-interfaces/interfaces/interface",
"ietf-interfaces/interfaces/interface/name",
"ietf-interfaces/interfaces/interface/description",
"ietf-interfaces/interfaces/interface/type",
"ietf-interfaces/interfaces/interface/enabled",
"ietf-ip/interfaces/interface/ipv4",
"ietf-ip/interfaces/interface/ipv4/enabled",
"ietf-ip/interfaces/interface/ipv4/forwarding",
"ietf-ip/interfaces/interface/ipv4/address",
"ietf-ip/interfaces/interface/ipv4/address/ip",
"ietf-ip/interfaces/interface/ipv4/address/subnet",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/netmask",
"hfr-base-spec/interfaces/interface/ipv4/address/secondary",
"ieee802-ethernet-interface/interfaces/interface/ethernet",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation/enable",
"ieee802-ethernet-interface/interfaces/interface/ethernet/duplex",
"ieee802-ethernet-interface/interfaces/interface/ethernet/speed",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause/direction",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/force-flow-control",
"bbf-fastdsl/interfaces/interface/line",
"bbf-fastdsl/interfaces/interface/line/configured-mode",
"bbf-fast/interfaces/interface/line/line",
"bbf-fast/interfaces/interface/line/line/profile-config",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode/line-config-vector",
"bbf-fast/interfaces/interface/line/line/threshold-template",
"bbf-fast/interfaces/interface/line/line/test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/rtx-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/tps-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/dra-test-mode",
"bbf-fast/interfaces/interface/line/line/update-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o/update-ne-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r/update-fe-test",
"bbf-fast/interfaces/interface/line/line/read-test",
"bbf-fast/interfaces/interface/line/line/read-test/downstream",
"bbf-fast/interfaces/interface/line/line/read-test/downstream/xlog-disturber-vce-port-index",
"bbf-fast/interfaces/interface/line/line/link-state",
"bbf-fast/interfaces/interface/line/line/link-state/link-state-forced",
"ietf-system/system",
"ietf-system/system/contact",
"ietf-system/system/hostname",
"ietf-system/system/location",
"ietf-system/system/clock",
"ietf-system/system/clock/timezone",
"ietf-system/system/clock/timezone/timezone-utc-offset",
"ietf-system/system/clock/timezone/timezone-utc-offset/timezone-utc-offset",
"ietf-system/system/dns-resolver",
"ietf-system/system/dns-resolver/search",
"ietf-system/system/dns-resolver/server",
"ietf-system/system/dns-resolver/server/name",
"ietf-system/system/dns-resolver/server/transport",
"ietf-system/system/dns-resolver/server/transport/udp-and-tcp",
"ietf-system/system/dns-resolver/server/transport/udp-and-tcp/udp-and-tcp",
"ietf-system/system/dns-resolver/server/transport/udp-and-tcp/udp-and-tcp/address",
"ietf-system/system/dns-resolver/options",
"ietf-system/system/dns-resolver/options/timeout",
"ietf-system/system/dns-resolver/options/attempts",
"hfr-vlan/vlans",
"hfr-vlan/vlans/vlan",
"hfr-vlan/vlans/vlan/id",
"hfr-vlan/create-vlan",
"hfr-vlan/delete-vlan",
"ietf-interfaces/interfaces",
"ietf-interfaces/interfaces/interface",
"ietf-interfaces/interfaces/interface/name",
"ietf-interfaces/interfaces/interface/description",
"ietf-interfaces/interfaces/interface/type",
"ietf-interfaces/interfaces/interface/enabled",
"ietf-ip/interfaces/interface/ipv4",
"ietf-ip/interfaces/interface/ipv4/enabled",
"ietf-ip/interfaces/interface/ipv4/forwarding",
"ietf-ip/interfaces/interface/ipv4/address",
"ietf-ip/interfaces/interface/ipv4/address/ip",
"ietf-ip/interfaces/interface/ipv4/address/subnet",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/netmask",
"hfr-base-spec/interfaces/interface/ipv4/address/secondary",
"ieee802-ethernet-interface/interfaces/interface/ethernet",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation/enable",
"ieee802-ethernet-interface/interfaces/interface/ethernet/duplex",
"ieee802-ethernet-interface/interfaces/interface/ethernet/speed",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause/direction",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/force-flow-control",
"bbf-fastdsl/interfaces/interface/line",
"bbf-fastdsl/interfaces/interface/line/configured-mode",
"bbf-fast/interfaces/interface/line/line",
"bbf-fast/interfaces/interface/line/line/profile-config",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode/line-config-vector",
"bbf-fast/interfaces/interface/line/line/threshold-template",
"bbf-fast/interfaces/interface/line/line/test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/rtx-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/tps-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/dra-test-mode",
"bbf-fast/interfaces/interface/line/line/update-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o/update-ne-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r/update-fe-test",
"bbf-fast/interfaces/interface/line/line/read-test",
"bbf-fast/interfaces/interface/line/line/read-test/downstream",
"bbf-fast/interfaces/interface/line/line/read-test/downstream/xlog-disturber-vce-port-index",
"bbf-fast/interfaces/interface/line/line/link-state",
"bbf-fast/interfaces/interface/line/line/link-state/link-state-forced",
"ietf-interfaces/interfaces",
"ietf-interfaces/interfaces/interface",
"ietf-interfaces/interfaces/interface/name",
"ietf-interfaces/interfaces/interface/description",
"ietf-interfaces/interfaces/interface/type",
"ietf-interfaces/interfaces/interface/enabled",
"ietf-ip/interfaces/interface/ipv4",
"ietf-ip/interfaces/interface/ipv4/enabled",
"ietf-ip/interfaces/interface/ipv4/forwarding",
"ietf-ip/interfaces/interface/ipv4/address",
"ietf-ip/interfaces/interface/ipv4/address/ip",
"ietf-ip/interfaces/interface/ipv4/address/subnet",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length",
"ietf-ip/interfaces/interface/ipv4/address/subnet/netmask",
"hfr-base-spec/interfaces/interface/ipv4/address/secondary",
"ieee802-ethernet-interface/interfaces/interface/ethernet",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation",
"ieee802-ethernet-interface/interfaces/interface/ethernet/auto-negotiation/enable",
"ieee802-ethernet-interface/interfaces/interface/ethernet/duplex",
"ieee802-ethernet-interface/interfaces/interface/ethernet/speed",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/pause/direction",
"ieee802-ethernet-interface/interfaces/interface/ethernet/flow-control/force-flow-control",
"bbf-fastdsl/interfaces/interface/line",
"bbf-fastdsl/interfaces/interface/line/configured-mode",
"bbf-fast/interfaces/interface/line/line",
"bbf-fast/interfaces/interface/line/line/profile-config",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/no-profiles-attached/no-profiles-attached",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode",
"bbf-fast/interfaces/interface/line/line/profile-config/indirect-attachment-mode/line-config-vector",
"bbf-fast/interfaces/interface/line/line/threshold-template",
"bbf-fast/interfaces/interface/line/line/test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/rtx-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/tps-tc-test-mode",
"bbf-fast/interfaces/interface/line/line/test-mode/dra-test-mode",
"bbf-fast/interfaces/interface/line/line/update-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-o/update-ne-test",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r",
"bbf-fast/interfaces/interface/line/line/update-test/ftu-r/update-fe-test",
"bbf-fast/interfaces/interface/line/line/read-test",
"bbf-fast/interfaces/interface/line/line/read-test/downstream",
"bbf-fast/interfaces/interface/line/line/read-test/downstream/xlog-disturber-vce-port-index",
"bbf-fast/interfaces/interface/line/line/link-state",
"bbf-fast/interfaces/interface/line/line/link-state/link-state-forced",
"bbf-fast/fast",
"bbf-fast/fast/service",
"bbf-fast/fast/service/downstream-data-rate-profile",
"bbf-fast/fast/service/downstream-data-rate-profile/name",
"bbf-fast/fast/service/downstream-data-rate-profile/maximum-net-data-rate",
"bbf-fast/fast/service/downstream-data-rate-profile/minimum-expected-throughput",
"bbf-fast/fast/service/downstream-data-rate-profile/maximum-gamma-data-rate",
"bbf-fast/fast/service/downstream-data-rate-profile/minimum-gamma-data-rate",
"bbf-fast/fast/service/upstream-data-rate-profile",
"bbf-fast/fast/service/upstream-data-rate-profile/name",
"bbf-fast/fast/service/upstream-data-rate-profile/maximum-net-data-rate",
"bbf-fast/fast/service/upstream-data-rate-profile/minimum-expected-throughput",
"bbf-fast/fast/service/upstream-data-rate-profile/maximum-gamma-data-rate",
"bbf-fast/fast/service/upstream-data-rate-profile/minimum-gamma-data-rate",
"bbf-fast/fast/service/time-division-duplexing-profile",
"bbf-fast/fast/service/time-division-duplexing-profile/name",
"bbf-fast/fast/service/time-division-duplexing-profile/total-symbol-periods",
"bbf-fast/fast/service/time-division-duplexing-profile/downstream-symbol-periods",
"bbf-fast/fast/service/time-division-duplexing-profile/cyclic-extension",
"bbf-fast/fast/spectrum",
"bbf-fast/fast/spectrum/line-spectrum-profile",
"bbf-fast/fast/spectrum/line-spectrum-profile/name",
"bbf-fast/fast/spectrum/line-spectrum-profile/profiles",
"bbf-fast/fast/spectrum/line-spectrum-profile/link-state-enabling",
"bbf-fast/fast/spectrum/line-spectrum-profile/maximum-psd-reduction-in-l2",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/maximum-aggregate-transmit-power",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/carmask",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/carmask/start-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/carmask/stop-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/mibpsdmask",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/mibpsdmask/sub-carrier-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/downstream/mibpsdmask/psd-level",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/maximum-aggregate-transmit-power",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/carmask",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/carmask/start-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/carmask/stop-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/mibpsdmask",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/mibpsdmask/sub-carrier-index",
"bbf-fast/fast/spectrum/line-spectrum-profile/upstream/mibpsdmask/psd-level",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile/name",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile/rfiband",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile/rfiband/start-index",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile/rfiband/stop-index",
"bbf-fast/fast/spectrum/radio-frequency-interference-profile/iarbands",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/name",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/upbopsd-a",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/upbopsd-b",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/upbo-upstream-electrical-length",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/upbo-force-electrical-length",
"bbf-fast/fast/spectrum/upstream-power-back-off-profile/upbo-reference-electrical-length",
"bbf-fast/fast/quality",
"bbf-fast/fast/quality/noise-margin-profile",
"bbf-fast/fast/quality/noise-margin-profile/name",
"bbf-fast/fast/quality/noise-margin-profile/downstream",
"bbf-fast/fast/quality/noise-margin-profile/downstream/noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/noise-margin/target-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/noise-margin/minimum-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/noise-margin/target-noise-margin-in-l2",
"bbf-fast/fast/quality/noise-margin-profile/downstream/noise-margin/maximum-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/upshift-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/upshift-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/minimum-time-interval-upshift-sra",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/downshift-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/downshift-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/downstream/seamless-rate-adaptation/minimum-time-interval-downshift-sra",
"bbf-fast/fast/quality/noise-margin-profile/downstream/robust-management-channel",
"bbf-fast/fast/quality/noise-margin-profile/downstream/robust-management-channel/target-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/robust-management-channel/minimum-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/downstream/robust-management-channel/maximum-bit-loading",
"bbf-fast/fast/quality/noise-margin-profile/upstream",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin/target-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin/minimum-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin/maximum-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin/target-noise-margin-in-l2",
"bbf-fast/fast/quality/noise-margin-profile/upstream/noise-margin/maximum-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/upshift-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/upshift-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/minimum-time-interval-upshift-sra",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/downshift-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/downshift-noise-margin-in-l2.1",
"bbf-fast/fast/quality/noise-margin-profile/upstream/seamless-rate-adaptation/minimum-time-interval-downshift-sra",
"bbf-fast/fast/quality/noise-margin-profile/upstream/robust-management-channel",
"bbf-fast/fast/quality/noise-margin-profile/upstream/robust-management-channel/target-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/robust-management-channel/minimum-noise-margin",
"bbf-fast/fast/quality/noise-margin-profile/upstream/robust-management-channel/maximum-bit-loading",
"bbf-fast/fast/quality/fast-rate-adaptation-profile",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/name",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/downstream",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/downstream/time-window",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/downstream/minimum-degraded-tones",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/downstream/uncorrectable-dtu",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/downstream/vendor-discretionary-fra-triggering-criteria",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/upstream",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/upstream/time-window",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/upstream/minimum-degraded-tones",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/upstream/uncorrectable-dtu",
"bbf-fast/fast/quality/fast-rate-adaptation-profile/upstream/vendor-discretionary-fra-triggering-criteria",
"bbf-fast/fast/quality/vectoring-profile",
"bbf-fast/fast/quality/vectoring-profile/name",
"bbf-fast/fast/quality/vectoring-profile/downstream",
"bbf-fast/fast/quality/vectoring-profile/downstream/fext-to-cancel-enable",
"bbf-fast/fast/quality/vectoring-profile/downstream/xlog-group-size-req",
"bbf-fast/fast/quality/vectoring-profile/upstream",
"bbf-fast/fast/quality/vectoring-profile/upstream/fext-to-cancel-enable",
"bbf-fast/fast/quality/fast-retrain-policy-profile",
"bbf-fast/fast/quality/fast-retrain-policy-profile/name",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream/los-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream/lom-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream/lor-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream/reinit-time-threshold",
"bbf-fast/fast/quality/fast-retrain-policy-profile/downstream/low-etr-threshold",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream/los-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream/lom-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream/lor-defect-persistency",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream/reinit-time-threshold",
"bbf-fast/fast/quality/fast-retrain-policy-profile/upstream/low-etr-threshold",
"bbf-fast/fast/quality/retransmission-profile",
"bbf-fast/fast/quality/retransmission-profile/name",
"bbf-fast/fast/quality/retransmission-profile/downstream",
"bbf-fast/fast/quality/retransmission-profile/downstream/maximum-delay",
"bbf-fast/fast/quality/retransmission-profile/downstream/minimum-inp-against-shine",
"bbf-fast/fast/quality/retransmission-profile/downstream/shine-ratio",
"bbf-fast/fast/quality/retransmission-profile/downstream/minimum-inp-against-rein",
"bbf-fast/fast/quality/retransmission-profile/downstream/rein-inter-arrival-time",
"bbf-fast/fast/quality/retransmission-profile/downstream/minimum-rfec-nfec-ratio",
"bbf-fast/fast/quality/retransmission-profile/upstream",
"bbf-fast/fast/quality/retransmission-profile/upstream/maximum-delay",
"bbf-fast/fast/quality/retransmission-profile/upstream/minimum-inp-against-shine",
"bbf-fast/fast/quality/retransmission-profile/upstream/shine-ratio",
"bbf-fast/fast/quality/retransmission-profile/upstream/minimum-inp-against-rein",
"bbf-fast/fast/quality/retransmission-profile/upstream/rein-inter-arrival-time",
"bbf-fast/fast/quality/retransmission-profile/upstream/minimum-rfec-nfec-ratio",
"bbf-fast/fast/thresholds",
"bbf-fast/fast/thresholds/line-threshold-profile",
"bbf-fast/fast/thresholds/line-threshold-profile/name",
"bbf-fast/fast/thresholds/line-threshold-profile/errored-seconds-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/severely-errored-seconds-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/loss-of-signal-seconds-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/loss-of-rmc-seconds-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/unavailable-seconds-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/full-initializations-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/failed-initializations-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/fast-initializations-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/failed-fast-initializations-threshold",
"bbf-fast/fast/thresholds/line-threshold-profile/spontaneous-interruptions-threshold",
"bbf-fast/fast/thresholds/channel-threshold-profile",
"bbf-fast/fast/thresholds/channel-threshold-profile/name",
"bbf-fast/fast/thresholds/channel-threshold-profile/code-violations-threshold",
"bbf-fast/fast/thresholds/channel-threshold-profile/uncorrectable-dtus-threshold",
"bbf-fast/fast/thresholds/channel-threshold-profile/retransmitted-dtus-threshold",
"bbf-fast/fast/thresholds/threshold-template",
"bbf-fast/fast/thresholds/threshold-template/name",
"bbf-fast/fast/thresholds/threshold-template/ftu-o-15min-line-threshold-profile",
"bbf-fast/fast/thresholds/threshold-template/ftu-r-15min-line-threshold-profile",
"bbf-fast/fast/thresholds/threshold-template/ftu-o-15min-channel-threshold-profile",
"bbf-fast/fast/thresholds/threshold-template/ftu-r-15min-channel-threshold-profile",
"bbf-fast/fast/vectors",
"bbf-fast/fast/vectors/line-config-vector",
"bbf-fast/fast/vectors/line-config-vector/name",
"bbf-fast/fast/vectors/line-config-vector/time-division-duplexing-profile",
"bbf-fast/fast/vectors/line-config-vector/downstream-data-rate-profile",
"bbf-fast/fast/vectors/line-config-vector/upstream-data-rate-profile",
"bbf-fast/fast/vectors/line-config-vector/line-spectrum-profile",
"bbf-fast/fast/vectors/line-config-vector/upstream-power-back-off-profile",
"bbf-fast/fast/vectors/line-config-vector/radio-frequency-interference-profile",
"bbf-fast/fast/vectors/line-config-vector/noise-margin-profile",
"bbf-fast/fast/vectors/line-config-vector/fast-rate-adaptation-profile",
"bbf-fast/fast/vectors/line-config-vector/retransmission-profile",
"bbf-fast/fast/vectors/line-config-vector/fast-retrain-policy-profile",
"bbf-fast/fast/vectors/line-config-vector/vectoring-profile",
		};
		for(i=0; i < (sizeof(item2)/sizeof(char *)); i++)
		{
			deleted = ytrie_delete(trie, item2[i], strlen(item2[i]));
			if(deleted) {
				printf("[DELETE] %s (%ld)\n", item2[i], strlen(item2[i]));
				free(deleted);
			}
			else {
				printf("[XXX] %s (%ld)\n", item2[i], strlen(item2[i]));
			}
		}
		delete_using_prefix(trie, "bbf-fast");

		ytrie_destroy_custom(trie, free);
		fclose(fp);
	}
	return 0;
}