/*
Package gostruct is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/neoul/go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- ../yang/example.yang
	- ../yang/sample.yang
Imported modules were sourced from:
	- yang/...
*/
package gostruct

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
	gpb "github.com/openconfig/gnmi/proto/gnmi"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

// UnionInt8 is an int8 type assignable to unions of which it is a subtype.
type UnionInt8 int8

// UnionInt16 is an int16 type assignable to unions of which it is a subtype.
type UnionInt16 int16

// UnionInt32 is an int32 type assignable to unions of which it is a subtype.
type UnionInt32 int32

// UnionInt64 is an int64 type assignable to unions of which it is a subtype.
type UnionInt64 int64

// UnionUint8 is a uint8 type assignable to unions of which it is a subtype.
type UnionUint8 uint8

// UnionUint16 is a uint16 type assignable to unions of which it is a subtype.
type UnionUint16 uint16

// UnionUint32 is a uint32 type assignable to unions of which it is a subtype.
type UnionUint32 uint32

// UnionUint64 is a uint64 type assignable to unions of which it is a subtype.
type UnionUint64 uint64

// UnionFloat64 is a float64 type assignable to unions of which it is a subtype.
type UnionFloat64 float64

// UnionString is a string type assignable to unions of which it is a subtype.
type UnionString string

// UnionBool is a bool type assignable to unions of which it is a subtype.
type UnionBool bool

// UnionUnsupported is an interface{} wrapper type for unsupported types. It is
// assignable to unions of which it is a subtype.
type UnionUnsupported struct {
	Value interface{}
}

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}
// ΓModelData contains the catalogue information corresponding to the modules for
// which Go code was generated.
var ΓModelData = []*gpb.ModelData{
    {
		Name: "network",
		Organization: "Actus Networks",
	},
    {
		Name: "sample",
		Organization: "sample model",
	},
}

// Device represents the /device YANG schema element.
type Device struct {
	Company	*Network_Company	`path:"company"`
	Country	map[string]*Network_Country	`path:"country"`
	Married	YANGEmpty	`path:"married"`
	Multikeylist	map[Device_Multikeylist_Key]*Network_Multikeylist	`path:"multikeylist"`
	Operator	map[uint32]*Network_Operator	`path:"operator"`
	Person	*string	`path:"person"`
	Sample	*Sample_Sample	`path:"sample"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Device_Multikeylist_Key represents the key for list Multikeylist of element /device.
type Device_Multikeylist_Key struct {
	Str	string	`path:"str"`
	Integer	uint32	`path:"integer"`
}

// NewCountry creates a new entry in the Country list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewCountry(Name string) (*Network_Country, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Country == nil {
		t.Country = make(map[string]*Network_Country)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Country[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Country", key)
	}

	t.Country[key] = &Network_Country{
		Name: &Name,
	}

	return t.Country[key], nil
}

// NewMultikeylist creates a new entry in the Multikeylist list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewMultikeylist(Str string, Integer uint32) (*Network_Multikeylist, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Multikeylist == nil {
		t.Multikeylist = make(map[Device_Multikeylist_Key]*Network_Multikeylist)
	}

	key := Device_Multikeylist_Key{
		Str: Str,
		Integer: Integer,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Multikeylist[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Multikeylist", key)
	}

	t.Multikeylist[key] = &Network_Multikeylist{
		Str: &Str,
		Integer: &Integer,
	}

	return t.Multikeylist[key], nil
}

// NewOperator creates a new entry in the Operator list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewOperator(Asn uint32) (*Network_Operator, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Operator == nil {
		t.Operator = make(map[uint32]*Network_Operator)
	}

	key := Asn

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Operator[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Operator", key)
	}

	t.Operator[key] = &Network_Operator{
		Asn: &Asn,
	}

	return t.Operator[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Company represents the /network/company YANG schema element.
type Network_Company struct {
	Address	[]string	`path:"address"`
	Enumval	E_Network_Company_Enumval	`path:"enumval"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Company implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Company) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Company) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Company"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Company) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Country represents the /network/country YANG schema element.
type Network_Country struct {
	CountryCode	*string	`path:"country-code"`
	DialCode	*uint32	`path:"dial-code"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Country implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Country) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Country struct, which is a YANG list entry.
func (t *Network_Country) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Country) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Country"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Country) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Multikeylist represents the /network/multikeylist YANG schema element.
type Network_Multikeylist struct {
	Integer	*uint32	`path:"integer"`
	Ok	*bool	`path:"ok"`
	Str	*string	`path:"str"`
}

// IsYANGGoStruct ensures that Network_Multikeylist implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Multikeylist) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Multikeylist struct, which is a YANG list entry.
func (t *Network_Multikeylist) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Integer == nil {
		return nil, fmt.Errorf("nil value for key Integer")
	}

	if t.Str == nil {
		return nil, fmt.Errorf("nil value for key Str")
	}

	return map[string]interface{}{
		"integer": *t.Integer,
		"str": *t.Str,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Multikeylist) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Multikeylist"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Multikeylist) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Operator represents the /network/operator YANG schema element.
type Network_Operator struct {
	Asn	*uint32	`path:"asn"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Operator implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Operator) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Operator struct, which is a YANG list entry.
func (t *Network_Operator) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Asn == nil {
		return nil, fmt.Errorf("nil value for key Asn")
	}

	return map[string]interface{}{
		"asn": *t.Asn,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Operator) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Operator"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Operator) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample represents the /sample/sample YANG schema element.
type Sample_Sample struct {
	ContainerVal	*Sample_Sample_ContainerVal	`path:"container-val"`
	EmptyVal	YANGEmpty	`path:"empty-val"`
	MultipleKeyList	map[Sample_Sample_MultipleKeyList_Key]*Sample_Sample_MultipleKeyList	`path:"multiple-key-list"`
	SingleKeyList	map[string]*Sample_Sample_SingleKeyList	`path:"single-key-list"`
	StrVal	*string	`path:"str-val"`
}

// IsYANGGoStruct ensures that Sample_Sample implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample) IsYANGGoStruct() {}

// Sample_Sample_MultipleKeyList_Key represents the key for list MultipleKeyList of element /sample/sample.
type Sample_Sample_MultipleKeyList_Key struct {
	Str	string	`path:"str"`
	Integer	uint32	`path:"integer"`
}

// NewMultipleKeyList creates a new entry in the MultipleKeyList list of the
// Sample_Sample struct. The keys of the list are populated from the input
// arguments.
func (t *Sample_Sample) NewMultipleKeyList(Str string, Integer uint32) (*Sample_Sample_MultipleKeyList, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.MultipleKeyList == nil {
		t.MultipleKeyList = make(map[Sample_Sample_MultipleKeyList_Key]*Sample_Sample_MultipleKeyList)
	}

	key := Sample_Sample_MultipleKeyList_Key{
		Str: Str,
		Integer: Integer,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.MultipleKeyList[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list MultipleKeyList", key)
	}

	t.MultipleKeyList[key] = &Sample_Sample_MultipleKeyList{
		Str: &Str,
		Integer: &Integer,
	}

	return t.MultipleKeyList[key], nil
}

// NewSingleKeyList creates a new entry in the SingleKeyList list of the
// Sample_Sample struct. The keys of the list are populated from the input
// arguments.
func (t *Sample_Sample) NewSingleKeyList(ListKey string) (*Sample_Sample_SingleKeyList, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.SingleKeyList == nil {
		t.SingleKeyList = make(map[string]*Sample_Sample_SingleKeyList)
	}

	key := ListKey

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.SingleKeyList[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list SingleKeyList", key)
	}

	t.SingleKeyList[key] = &Sample_Sample_SingleKeyList{
		ListKey: &ListKey,
	}

	return t.SingleKeyList[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample_ContainerVal represents the /sample/sample/container-val YANG schema element.
type Sample_Sample_ContainerVal struct {
	EnumVal	E_Sample_Sample_ContainerVal_EnumVal	`path:"enum-val"`
	LeafListV2	[]int32	`path:"leaf-list-v2"`
	LeafListVal	[]string	`path:"leaf-list-val"`
	UnionValue	Sample_Sample_ContainerVal_UnionValue_Union	`path:"union-value"`
}

// IsYANGGoStruct ensures that Sample_Sample_ContainerVal implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_ContainerVal) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_ContainerVal) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_ContainerVal"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_ContainerVal) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// Sample_Sample_ContainerVal_UnionValue_Union is an interface that is implemented by valid types for the union
// for the leaf /sample/sample/container-val/union-value within the YANG schema.
// Union type can be one of [E_Sample_Enumtypedef_Enum, UnionString, UnionUint16].
type Sample_Sample_ContainerVal_UnionValue_Union interface {
	// Union type can be one of [E_Sample_Enumtypedef_Enum, UnionString, UnionUint16]
	Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union()
}

// Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union ensures that E_Sample_Enumtypedef_Enum
// implements the Sample_Sample_ContainerVal_UnionValue_Union interface.
func (E_Sample_Enumtypedef_Enum) Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union() {}

// Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union ensures that UnionString
// implements the Sample_Sample_ContainerVal_UnionValue_Union interface.
func (UnionString) Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union() {}

// Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union ensures that UnionUint16
// implements the Sample_Sample_ContainerVal_UnionValue_Union interface.
func (UnionUint16) Documentation_for_Sample_Sample_ContainerVal_UnionValue_Union() {}

// To_Sample_Sample_ContainerVal_UnionValue_Union takes an input interface{} and attempts to convert it to a struct
// which implements the Sample_Sample_ContainerVal_UnionValue_Union union. It returns an error if the interface{} supplied
// cannot be converted to a type within the union.
func (t *Sample_Sample_ContainerVal) To_Sample_Sample_ContainerVal_UnionValue_Union(i interface{}) (Sample_Sample_ContainerVal_UnionValue_Union, error) {
	if v, ok := i.(Sample_Sample_ContainerVal_UnionValue_Union); ok {
		return v, nil
	}
	switch v := i.(type) {
	case string:
		return UnionString(v), nil
	case uint16:
		return UnionUint16(v), nil
	}
	return nil, fmt.Errorf("cannot convert %v to Sample_Sample_ContainerVal_UnionValue_Union, unknown union type, got: %T, want any of [E_Sample_Enumtypedef_Enum, string, uint16]", i, i)
}


// Sample_Sample_MultipleKeyList represents the /sample/sample/multiple-key-list YANG schema element.
type Sample_Sample_MultipleKeyList struct {
	Integer	*uint32	`path:"integer"`
	Ok	*bool	`path:"ok"`
	Str	*string	`path:"str"`
}

// IsYANGGoStruct ensures that Sample_Sample_MultipleKeyList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_MultipleKeyList) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Sample_Sample_MultipleKeyList struct, which is a YANG list entry.
func (t *Sample_Sample_MultipleKeyList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Integer == nil {
		return nil, fmt.Errorf("nil value for key Integer")
	}

	if t.Str == nil {
		return nil, fmt.Errorf("nil value for key Str")
	}

	return map[string]interface{}{
		"integer": *t.Integer,
		"str": *t.Str,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_MultipleKeyList) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_MultipleKeyList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_MultipleKeyList) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample_SingleKeyList represents the /sample/sample/single-key-list YANG schema element.
type Sample_Sample_SingleKeyList struct {
	CountryCode	*string	`path:"country-code"`
	DialCode	*uint32	`path:"dial-code"`
	ListKey	*string	`path:"list-key"`
}

// IsYANGGoStruct ensures that Sample_Sample_SingleKeyList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_SingleKeyList) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Sample_Sample_SingleKeyList struct, which is a YANG list entry.
func (t *Sample_Sample_SingleKeyList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.ListKey == nil {
		return nil, fmt.Errorf("nil value for key ListKey")
	}

	return map[string]interface{}{
		"list-key": *t.ListKey,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_SingleKeyList) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_SingleKeyList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_SingleKeyList) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_Network_Company_Enumval is a derived int64 type which is used to represent
// the enumerated node Network_Company_Enumval. An additional value named
// Network_Company_Enumval_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Network_Company_Enumval int64

// IsYANGGoEnum ensures that Network_Company_Enumval implements the yang.GoEnum
// interface. This ensures that Network_Company_Enumval can be identified as a
// mapped type for a YANG enumeration.
func (E_Network_Company_Enumval) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Network_Company_Enumval.
func (E_Network_Company_Enumval) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Network_Company_Enumval.
func (e E_Network_Company_Enumval) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Network_Company_Enumval")
}

const (
	// Network_Company_Enumval_UNSET corresponds to the value UNSET of Network_Company_Enumval
	Network_Company_Enumval_UNSET E_Network_Company_Enumval = 0
	// Network_Company_Enumval_enum1 corresponds to the value enum1 of Network_Company_Enumval
	Network_Company_Enumval_enum1 E_Network_Company_Enumval = 1
	// Network_Company_Enumval_enum2 corresponds to the value enum2 of Network_Company_Enumval
	Network_Company_Enumval_enum2 E_Network_Company_Enumval = 2
	// Network_Company_Enumval_enum3 corresponds to the value enum3 of Network_Company_Enumval
	Network_Company_Enumval_enum3 E_Network_Company_Enumval = 31
)


// E_Sample_Enumtypedef_Enum is a derived int64 type which is used to represent
// the enumerated node Sample_Enumtypedef_Enum. An additional value named
// Sample_Enumtypedef_Enum_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Sample_Enumtypedef_Enum int64

// IsYANGGoEnum ensures that Sample_Enumtypedef_Enum implements the yang.GoEnum
// interface. This ensures that Sample_Enumtypedef_Enum can be identified as a
// mapped type for a YANG enumeration.
func (E_Sample_Enumtypedef_Enum) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Sample_Enumtypedef_Enum.
func (E_Sample_Enumtypedef_Enum) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Sample_Enumtypedef_Enum.
func (e E_Sample_Enumtypedef_Enum) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Sample_Enumtypedef_Enum")
}

const (
	// Sample_Enumtypedef_Enum_UNSET corresponds to the value UNSET of Sample_Enumtypedef_Enum
	Sample_Enumtypedef_Enum_UNSET E_Sample_Enumtypedef_Enum = 0
	// Sample_Enumtypedef_Enum_e1 corresponds to the value e1 of Sample_Enumtypedef_Enum
	Sample_Enumtypedef_Enum_e1 E_Sample_Enumtypedef_Enum = 1
	// Sample_Enumtypedef_Enum_e2 corresponds to the value e2 of Sample_Enumtypedef_Enum
	Sample_Enumtypedef_Enum_e2 E_Sample_Enumtypedef_Enum = 2
	// Sample_Enumtypedef_Enum_e3 corresponds to the value e3 of Sample_Enumtypedef_Enum
	Sample_Enumtypedef_Enum_e3 E_Sample_Enumtypedef_Enum = 101
)


// E_Sample_Sample_ContainerVal_EnumVal is a derived int64 type which is used to represent
// the enumerated node Sample_Sample_ContainerVal_EnumVal. An additional value named
// Sample_Sample_ContainerVal_EnumVal_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Sample_Sample_ContainerVal_EnumVal int64

// IsYANGGoEnum ensures that Sample_Sample_ContainerVal_EnumVal implements the yang.GoEnum
// interface. This ensures that Sample_Sample_ContainerVal_EnumVal can be identified as a
// mapped type for a YANG enumeration.
func (E_Sample_Sample_ContainerVal_EnumVal) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Sample_Sample_ContainerVal_EnumVal.
func (E_Sample_Sample_ContainerVal_EnumVal) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Sample_Sample_ContainerVal_EnumVal.
func (e E_Sample_Sample_ContainerVal_EnumVal) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Sample_Sample_ContainerVal_EnumVal")
}

const (
	// Sample_Sample_ContainerVal_EnumVal_UNSET corresponds to the value UNSET of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_UNSET E_Sample_Sample_ContainerVal_EnumVal = 0
	// Sample_Sample_ContainerVal_EnumVal_enum1 corresponds to the value enum1 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum1 E_Sample_Sample_ContainerVal_EnumVal = 1
	// Sample_Sample_ContainerVal_EnumVal_enum2 corresponds to the value enum2 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum2 E_Sample_Sample_ContainerVal_EnumVal = 2
	// Sample_Sample_ContainerVal_EnumVal_enum3 corresponds to the value enum3 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum3 E_Sample_Sample_ContainerVal_EnumVal = 31
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Network_Company_Enumval": {
		1: {Name: "enum1"},
		2: {Name: "enum2"},
		31: {Name: "enum3"},
	},
	"E_Sample_Enumtypedef_Enum": {
		1: {Name: "e1"},
		2: {Name: "e2"},
		101: {Name: "e3"},
	},
	"E_Sample_Sample_ContainerVal_EnumVal": {
		1: {Name: "enum1"},
		2: {Name: "enum2"},
		31: {Name: "enum3"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5d, 0xdf, 0x6f, 0xdb, 0xb8,
		0x0f, 0x7f, 0xcf, 0x5f, 0x61, 0xf8, 0xb9, 0xc1, 0xf2, 0xc3, 0x49, 0x9a, 0xbe, 0xf5, 0xdb, 0x6e,
		0xf8, 0x02, 0x5d, 0xb7, 0xc3, 0x7a, 0xd8, 0xcb, 0xa1, 0x18, 0x74, 0x89, 0x9a, 0x09, 0xb1, 0x65,
		0x43, 0x96, 0xbb, 0x06, 0x87, 0xfc, 0xef, 0x87, 0xc4, 0x76, 0x1a, 0xc7, 0x96, 0x44, 0xd9, 0xce,
		0xad, 0x69, 0xf8, 0x14, 0xd4, 0x22, 0x6d, 0x4a, 0x24, 0xc5, 0x0f, 0x49, 0xcb, 0xfd, 0xa7, 0xe3,
		0x38, 0x8e, 0xe3, 0x7e, 0x21, 0x01, 0x75, 0xaf, 0x1c, 0x77, 0x4e, 0x9f, 0xd9, 0x8c, 0xba, 0x17,
		0xe9, 0xd5, 0x3b, 0xc6, 0xe7, 0xee, 0x95, 0xd3, 0xcf, 0xfe, 0xbc, 0x09, 0xf9, 0x13, 0x5b, 0xb8,
		0x57, 0x4e, 0x2f, 0xbb, 0x70, 0xcb, 0x84, 0x7b, 0xe5, 0xa4, 0xb7, 0xd8, 0x5e, 0x98, 0x85, 0x41,
		0x44, 0xf8, 0xaa, 0x70, 0xb1, 0x70, 0xff, 0x9c, 0xe0, 0xa2, 0x38, 0x5c, 0x7c, 0xd0, 0xee, 0xf2,
		0xe1, 0x03, 0x77, 0x03, 0x7f, 0x08, 0xfa, 0xc4, 0x5e, 0x4a, 0x8f, 0x29, 0x3c, 0x8a, 0x53, 0x79,
		0xf0, 0x98, 0xed, 0xf0, 0x43, 0x98, 0x88, 0x19, 0xad, 0x64, 0x4d, 0x45, 0xa1, 0xab, 0x5f, 0xa1,
		0xd8, 0x48, 0xe3, 0x46, 0xe9, 0x53, 0x2e, 0xaa, 0x09, 0xff, 0x4f, 0xe2, 0x6b, 0xb1, 0x48, 0x02,
		0xca, 0xa5, 0x7b, 0xe5, 0x48, 0x91, 0x50, 0x05, 0xe1, 0x1e, 0xd5, 0x56, 0xa8, 0x12, 0xd5, 0xba,
		0x70, 0x65, 0x7d, 0x30, 0xd7, 0xc3, 0x45, 0xde, 0x0d, 0x90, 0xf9, 0x5c, 0xd0, 0x38, 0x56, 0x4f,
		0x25, 0x5f, 0x89, 0x9c, 0x50, 0x21, 0x5f, 0xb6, 0xf8, 0x3d, 0xc5, 0xb0, 0x4a, 0x09, 0x10, 0x65,
		0x00, 0x95, 0x02, 0x55, 0x8e, 0xb5, 0x92, 0xac, 0x95, 0x05, 0x57, 0x5a, 0xb5, 0xf2, 0x14, 0x4a,
		0xdc, 0xdd, 0xf6, 0xcf, 0x55, 0x44, 0x61, 0x2b, 0x15, 0x4b, 0xc1, 0xf8, 0x42, 0xb7, 0x58, 0xb9,
		0xd3, 0x5c, 0x5a, 0x49, 0xf0, 0x99, 0xc5, 0xf2, 0x5a, 0x4a, 0xa1, 0x97, 0xe2, 0x9e, 0xf1, 0x8f,
		0x3e, 0xdd, 0x2c, 0x40, 0xac, 0xd6, 0x7c, 0x4a, 0x49, 0x5e, 0xf6, 0x28, 0xfb, 0x97, 0x9e, 0x37,
		0x9e, 0x78, 0x5e, 0x6f, 0x32, 0x9c, 0xf4, 0xa6, 0xa3, 0x51, 0x7f, 0xdc, 0x1f, 0x69, 0x98, 0xbf,
		0x8a, 0x39, 0x15, 0x74, 0xfe, 0xbf, 0xcd, 0x8e, 0xc1, 0x13, 0xdf, 0xef, 0xc0, 0x56, 0xb8, 0x62,
		0x6e, 0x2e, 0xe5, 0x49, 0xf0, 0x4c, 0x7c, 0xb3, 0x37, 0xe4, 0x84, 0xe8, 0x0d, 0x27, 0xe4, 0x0d,
		0x1b, 0xa5, 0x51, 0x41, 0x24, 0x0b, 0x39, 0xc4, 0x25, 0x3c, 0x0d, 0xcd, 0x47, 0x9e, 0x04, 0x9b,
		0x87, 0xae, 0x1b, 0x18, 0x1b, 0x4f, 0xc5, 0x32, 0x58, 0xda, 0x96, 0x0a, 0xcd, 0xec, 0x9c, 0x36,
		0x5d, 0xcb, 0xd8, 0x7e, 0xcd, 0x79, 0x28, 0x53, 0xab, 0xae, 0x0c, 0xf1, 0xf1, 0xec, 0x27, 0x0d,
		0x48, 0x44, 0xe4, 0xcf, 0x8d, 0x74, 0x1f, 0x38, 0x95, 0xbf, 0x42, 0xb1, 0xfc, 0x50, 0x8d, 0xa2,
		0x52, 0x0e, 0x29, 0x92, 0x99, 0xcc, 0xec, 0xd3, 0xfd, 0x92, 0x32, 0xfc, 0xb8, 0xc9, 0x18, 0x3a,
		0xd5, 0xa2, 0xed, 0x89, 0xe5, 0xce, 0xc2, 0x84, 0x4b, 0xa1, 0x85, 0x70, 0x29, 0x01, 0x42, 0xb8,
		0xe6, 0x10, 0x2e, 0x5b, 0xcb, 0xee, 0x2c, 0x9c, 0x03, 0xf6, 0x93, 0x02, 0x35, 0xee, 0x2b, 0xe7,
		0xbd, 0xaf, 0x54, 0xf8, 0xc5, 0x9c, 0x11, 0x1f, 0x68, 0x4a, 0xaf, 0xa4, 0x68, 0x47, 0x27, 0x64,
		0x47, 0x09, 0xe3, 0x72, 0x38, 0x00, 0xd8, 0xd1, 0x44, 0x43, 0xf2, 0x8d, 0xf0, 0xc5, 0xe6, 0x6e,
		0x7f, 0x69, 0x27, 0xab, 0x5f, 0xec, 0x3c, 0x49, 0x30, 0x6a, 0x05, 0x68, 0x50, 0x25, 0xf2, 0xef,
		0xc4, 0x4f, 0x68, 0x39, 0x9e, 0x28, 0xe9, 0x3f, 0x09, 0x32, 0xdb, 0xc4, 0xd1, 0x5b, 0xb6, 0x60,
		0x69, 0xce, 0x62, 0xe4, 0x5b, 0x5f, 0x00, 0xa6, 0x48, 0x5e, 0x8e, 0x3e, 0x45, 0x6f, 0x3a, 0x38,
		0xe2, 0x24, 0x3b, 0xf5, 0x46, 0x1f, 0x11, 0x1d, 0xe3, 0xee, 0xf3, 0x9b, 0xd1, 0xf1, 0x1d, 0x5d,
		0x29, 0x0c, 0x45, 0x5f, 0xc5, 0x30, 0x57, 0x2f, 0x6a, 0x55, 0x2d, 0xf4, 0xd5, 0x8a, 0xd6, 0xa0,
		0x7d, 0x15, 0xba, 0xd6, 0x42, 0xfb, 0x94, 0x01, 0x00, 0xed, 0x03, 0x22, 0x04, 0xa3, 0x73, 0x35,
		0xb4, 0xcf, 0x09, 0xaa, 0xa1, 0x7d, 0x0f, 0xa1, 0x7d, 0x59, 0xcd, 0x4a, 0xef, 0x79, 0x2d, 0x5d,
		0x04, 0x91, 0xac, 0xd4, 0x67, 0xee, 0x2c, 0x43, 0x88, 0xea, 0x12, 0x5f, 0xb2, 0x25, 0x5d, 0xf9,
		0x2c, 0x96, 0x1a, 0xfd, 0xed, 0x53, 0x61, 0x7e, 0xd6, 0x3c, 0x3f, 0x63, 0x5c, 0xd2, 0x05, 0x15,
		0xe6, 0x60, 0x96, 0x13, 0x62, 0x3c, 0x43, 0x34, 0xfd, 0x86, 0xd1, 0x74, 0xef, 0x0c, 0xd0, 0xf4,
		0x60, 0xea, 0x4d, 0xc7, 0x93, 0xc1, 0x74, 0xf4, 0xbe, 0x40, 0x75, 0xb8, 0x34, 0xef, 0x42, 0xe1,
		0x12, 0x37, 0xa0, 0x53, 0xda, 0x80, 0xfe, 0x0e, 0x43, 0x9f, 0x12, 0x50, 0x47, 0xa3, 0xdf, 0xc0,
		0x74, 0x62, 0x09, 0x88, 0x60, 0x1b, 0x22, 0x34, 0x1e, 0xcc, 0xc6, 0x4c, 0xd9, 0x58, 0x2c, 0x85,
		0x53, 0x8d, 0x76, 0xde, 0x6f, 0x52, 0xa6, 0xc1, 0xd5, 0x9a, 0xcc, 0xec, 0x7e, 0x9f, 0x0b, 0x80,
		0xf1, 0xc3, 0x88, 0x0a, 0x22, 0x43, 0xa1, 0xc6, 0xf7, 0x3b, 0x0a, 0xc4, 0xf6, 0xcd, 0xb1, 0x3d,
		0x89, 0x39, 0xe0, 0xd5, 0x99, 0x98, 0xe3, 0xae, 0x88, 0x98, 0x1e, 0x31, 0x3d, 0x62, 0x7a, 0x2c,
		0x94, 0xe3, 0x26, 0xf4, 0xb6, 0xa1, 0x59, 0x39, 0x58, 0xbd, 0x5f, 0x48, 0xa6, 0x80, 0x42, 0x1a,
		0x38, 0xf6, 0x35, 0xe7, 0x00, 0x40, 0xb1, 0x88, 0x8a, 0xb8, 0x42, 0xa0, 0x9d, 0x82, 0xb3, 0x71,
		0xac, 0x93, 0xb7, 0x58, 0x27, 0x57, 0x3a, 0x8d, 0xc2, 0x59, 0xaa, 0x35, 0x17, 0x93, 0x20, 0xf2,
		0xa9, 0x5a, 0x73, 0xd9, 0x38, 0x02, 0xe8, 0xe6, 0x00, 0x7a, 0x16, 0x72, 0x49, 0x18, 0xa7, 0xa2,
		0x0b, 0x7a, 0xef, 0xb6, 0x48, 0xae, 0x8f, 0x67, 0x7d, 0x8c, 0x67, 0xc7, 0x8f, 0x67, 0x2a, 0xc5,
		0xee, 0x08, 0x28, 0x4f, 0x02, 0xad, 0x6e, 0xcb, 0xbd, 0xae, 0x9c, 0xc3, 0x30, 0x23, 0x18, 0x0e,
		0x34, 0xaa, 0xdb, 0x46, 0xed, 0x96, 0xea, 0xb7, 0x35, 0x83, 0xda, 0xe6, 0x50, 0xdb, 0x2c, 0xec,
		0xcd, 0x03, 0x08, 0x75, 0x0d, 0x6b, 0x6d, 0x84, 0x41, 0x95, 0x56, 0x61, 0x7e, 0x79, 0xbb, 0xb4,
		0x07, 0x78, 0x00, 0x5a, 0xfd, 0xcb, 0xdc, 0xe6, 0x09, 0x6b, 0x26, 0xeb, 0xfa, 0x94, 0x3c, 0x75,
		0x7d, 0x16, 0xcb, 0xee, 0xf3, 0x00, 0xee, 0x02, 0x05, 0x2e, 0x74, 0x03, 0x74, 0x83, 0xfd, 0x1e,
		0xf1, 0x70, 0x60, 0xe1, 0x00, 0x43, 0x00, 0x29, 0xac, 0x52, 0x01, 0xaf, 0x58, 0xd4, 0xaa, 0x5c,
		0x00, 0xa3, 0xb7, 0x31, 0xcd, 0x1f, 0xf4, 0xbd, 0x89, 0x77, 0x39, 0x1c, 0x7b, 0x97, 0x96, 0x37,
		0xa8, 0x91, 0xee, 0x5b, 0x94, 0x38, 0x6a, 0x95, 0x3a, 0x6a, 0x96, 0x3c, 0xd4, 0x6b, 0x32, 0xf9,
		0x0f, 0xd7, 0xa4, 0xd3, 0x0e, 0xd5, 0x63, 0x23, 0x07, 0x03, 0x1d, 0x54, 0x83, 0xa7, 0xb2, 0xad,
		0xa4, 0xb6, 0x76, 0xa9, 0x6e, 0xeb, 0x61, 0xc8, 0x06, 0x8a, 0x15, 0xd9, 0x30, 0x10, 0x61, 0x20,
		0x82, 0x97, 0xa7, 0x80, 0x65, 0x2a, 0xf4, 0x64, 0x3b, 0x4f, 0x4e, 0x38, 0x0b, 0xf9, 0xc6, 0x1d,
		0x13, 0x0a, 0xf7, 0xe3, 0x7d, 0x26, 0xf4, 0x62, 0xf4, 0xe2, 0xa2, 0x61, 0xd8, 0x38, 0xf1, 0x14,
		0x40, 0x9b, 0x89, 0xd1, 0x3a, 0x9c, 0xdc, 0x6f, 0xcf, 0xf5, 0xc7, 0xae, 0x05, 0xe8, 0xca, 0xa4,
		0x1f, 0x5b, 0xb0, 0xd8, 0x81, 0x62, 0xfb, 0xd9, 0x34, 0x02, 0xc9, 0x0d, 0x81, 0x61, 0x09, 0x20,
		0xd6, 0xe5, 0x6f, 0x80, 0x0f, 0x6b, 0x60, 0xe7, 0x46, 0x18, 0xba, 0xed, 0x25, 0x1b, 0x8f, 0x46,
		0xc3, 0xd1, 0x6f, 0x5c, 0xb6, 0xce, 0x71, 0xa8, 0x1f, 0x3b, 0x2d, 0x2a, 0xad, 0x86, 0x6f, 0x83,
		0x61, 0x85, 0x25, 0xbc, 0x38, 0xbe, 0xe4, 0x94, 0x27, 0x81, 0x5c, 0x45, 0x74, 0x4e, 0x9f, 0xea,
		0x88, 0xef, 0x59, 0xf0, 0xc0, 0x0a, 0x56, 0xad, 0xe5, 0x58, 0x2d, 0x95, 0x8a, 0x0d, 0x4d, 0xba,
		0x1d, 0xdd, 0x41, 0xb3, 0x2e, 0x6d, 0xb6, 0xe4, 0x3f, 0x90, 0x06, 0x80, 0x53, 0xee, 0xdf, 0x3d,
		0x6c, 0xb9, 0x7f, 0x64, 0x3f, 0x37, 0xf9, 0x4d, 0xbe, 0x13, 0xdf, 0x6d, 0xf2, 0xb9, 0x90, 0x20,
		0x92, 0x2b, 0x58, 0xe3, 0xe2, 0x95, 0x14, 0x9b, 0xf0, 0xa7, 0xf4, 0xc9, 0x10, 0xc5, 0xb9, 0x9b,
		0x92, 0xfb, 0x0e, 0x1b, 0x98, 0xd1, 0xf6, 0xcd, 0xc0, 0xc8, 0xa7, 0xdd, 0x25, 0x5d, 0x75, 0x2b,
		0x0f, 0xe7, 0x94, 0xe4, 0x2a, 0xb3, 0x60, 0x2f, 0xec, 0xed, 0xf7, 0xc2, 0x4c, 0x27, 0x81, 0xaa,
		0xaa, 0xbd, 0x9a, 0x13, 0x41, 0x98, 0xb3, 0x9d, 0x67, 0xce, 0x66, 0xdb, 0x03, 0x98, 0x9c, 0x6a,
		0x0f, 0xa0, 0x6e, 0xbd, 0xbb, 0x87, 0xa5, 0xff, 0xba, 0x6f, 0x3d, 0x9e, 0x50, 0xe9, 0xbf, 0x56,
		0xf9, 0x4c, 0x73, 0x02, 0xaa, 0xe4, 0x68, 0xca, 0x93, 0x50, 0xb8, 0xf1, 0x9e, 0xe5, 0xc6, 0x6b,
		0x3e, 0x69, 0x55, 0x82, 0x5d, 0xfd, 0x23, 0x98, 0x70, 0x2c, 0x2d, 0x10, 0x84, 0xfa, 0x44, 0x16,
		0x1a, 0xf1, 0x59, 0x1a, 0x71, 0xeb, 0x7d, 0x9b, 0x96, 0xc0, 0xb3, 0xf1, 0x64, 0xd8, 0x8e, 0xf2,
		0x04, 0x3f, 0x3e, 0x7a, 0xcc, 0x8a, 0x08, 0x34, 0x15, 0x34, 0x56, 0x45, 0xee, 0xb3, 0x1b, 0xdd,
		0xd1, 0xd5, 0xe7, 0xd2, 0x69, 0x33, 0xbb, 0x8c, 0x36, 0x66, 0x7c, 0x61, 0x95, 0xcf, 0x1e, 0x32,
		0x60, 0x36, 0xfb, 0xf6, 0xb3, 0x59, 0xd0, 0x77, 0x07, 0x4b, 0xcb, 0x0a, 0xf8, 0xfe, 0x20, 0x46,
		0x26, 0x8c, 0x4c, 0xc7, 0x8d, 0x4c, 0x1a, 0xbf, 0x36, 0x7f, 0xff, 0xb0, 0x24, 0xb8, 0xe9, 0x3b,
		0x88, 0x68, 0xcf, 0x58, 0xa7, 0xc1, 0x3a, 0x4d, 0x45, 0x71, 0xa2, 0x8f, 0x75, 0x1a, 0xeb, 0xef,
		0x37, 0xbe, 0xf7, 0x02, 0xcd, 0xf6, 0x6d, 0xc3, 0x25, 0x5d, 0x59, 0xbc, 0xa4, 0x98, 0x73, 0xe0,
		0xee, 0x8b, 0xbb, 0xef, 0xa9, 0xe4, 0xb9, 0x06, 0xa3, 0xc5, 0x24, 0xb7, 0x98, 0xe4, 0xc2, 0xf2,
		0x43, 0x63, 0x8a, 0xfb, 0xb0, 0xbd, 0x4d, 0x1b, 0x09, 0xae, 0x04, 0x1e, 0x58, 0xcc, 0x09, 0xb1,
		0xeb, 0x8f, 0x47, 0xef, 0x55, 0x12, 0xda, 0x1e, 0x5f, 0x2f, 0xb8, 0x86, 0xf9, 0xec, 0x7a, 0xc1,
		0x05, 0x94, 0x07, 0xd7, 0x3b, 0x7b, 0x82, 0xa9, 0x04, 0x72, 0x59, 0xfc, 0x89, 0x2c, 0xe9, 0xb7,
		0x30, 0x2c, 0x6b, 0xf2, 0x50, 0x48, 0x77, 0x7f, 0xa8, 0x20, 0xcf, 0x6d, 0xfa, 0xef, 0xc1, 0xd2,
		0x07, 0x76, 0xd6, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xf9,
		0xa3, 0xa8, 0x3d, 0x6c, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/company/enumval": []reflect.Type{
		reflect.TypeOf((E_Network_Company_Enumval)(0)),
	},
	"/sample/container-val/enum-val": []reflect.Type{
		reflect.TypeOf((E_Sample_Sample_ContainerVal_EnumVal)(0)),
	},
	"/sample/container-val/union-value": []reflect.Type{
		reflect.TypeOf((E_Sample_Enumtypedef_Enum)(0)),
	},
}

