/*
Package gostruct is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/neoul/go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- ../yang/example.yang
	- ../yang/sample.yang
Imported modules were sourced from:
	- yang/...
*/
package gostruct

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
	gpb "github.com/openconfig/gnmi/proto/gnmi"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}
// ΓModelData contains the catalogue information corresponding to the modules for
// which Go code was generated.
var ΓModelData = []*gpb.ModelData{
    {
		Name: "network",
		Organization: "Actus Networks",
	},
    {
		Name: "sample",
		Organization: "sample model",
	},
}

// Device represents the /device YANG schema element.
type Device struct {
	Company	*Network_Company	`path:"company"`
	Country	map[string]*Network_Country	`path:"country"`
	Married	YANGEmpty	`path:"married"`
	Multikeylist	map[Device_Multikeylist_Key]*Network_Multikeylist	`path:"multikeylist"`
	Operator	map[uint32]*Network_Operator	`path:"operator"`
	Person	*string	`path:"person"`
	Sample	*Sample_Sample	`path:"sample"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Device_Multikeylist_Key represents the key for list Multikeylist of element /device.
type Device_Multikeylist_Key struct {
	Str	string	`path:"str"`
	Integer	uint32	`path:"integer"`
}

// NewCountry creates a new entry in the Country list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewCountry(Name string) (*Network_Country, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Country == nil {
		t.Country = make(map[string]*Network_Country)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Country[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Country", key)
	}

	t.Country[key] = &Network_Country{
		Name: &Name,
	}

	return t.Country[key], nil
}

// NewMultikeylist creates a new entry in the Multikeylist list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewMultikeylist(Str string, Integer uint32) (*Network_Multikeylist, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Multikeylist == nil {
		t.Multikeylist = make(map[Device_Multikeylist_Key]*Network_Multikeylist)
	}

	key := Device_Multikeylist_Key{
		Str: Str,
		Integer: Integer,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Multikeylist[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Multikeylist", key)
	}

	t.Multikeylist[key] = &Network_Multikeylist{
		Str: &Str,
		Integer: &Integer,
	}

	return t.Multikeylist[key], nil
}

// NewOperator creates a new entry in the Operator list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewOperator(Asn uint32) (*Network_Operator, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Operator == nil {
		t.Operator = make(map[uint32]*Network_Operator)
	}

	key := Asn

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Operator[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Operator", key)
	}

	t.Operator[key] = &Network_Operator{
		Asn: &Asn,
	}

	return t.Operator[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Company represents the /network/company YANG schema element.
type Network_Company struct {
	Address	[]string	`path:"address"`
	Enumval	E_Network_Company_Enumval	`path:"enumval"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Company implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Company) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Company) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Company"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Company) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Country represents the /network/country YANG schema element.
type Network_Country struct {
	CountryCode	*string	`path:"country-code"`
	DialCode	*uint32	`path:"dial-code"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Country implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Country) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Country struct, which is a YANG list entry.
func (t *Network_Country) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Country) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Country"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Country) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Multikeylist represents the /network/multikeylist YANG schema element.
type Network_Multikeylist struct {
	Integer	*uint32	`path:"integer"`
	Ok	*bool	`path:"ok"`
	Str	*string	`path:"str"`
}

// IsYANGGoStruct ensures that Network_Multikeylist implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Multikeylist) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Multikeylist struct, which is a YANG list entry.
func (t *Network_Multikeylist) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Integer == nil {
		return nil, fmt.Errorf("nil value for key Integer")
	}

	if t.Str == nil {
		return nil, fmt.Errorf("nil value for key Str")
	}

	return map[string]interface{}{
		"integer": *t.Integer,
		"str": *t.Str,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Multikeylist) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Multikeylist"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Multikeylist) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Operator represents the /network/operator YANG schema element.
type Network_Operator struct {
	Asn	*uint32	`path:"asn"`
	Name	*string	`path:"name"`
}

// IsYANGGoStruct ensures that Network_Operator implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Operator) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Operator struct, which is a YANG list entry.
func (t *Network_Operator) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Asn == nil {
		return nil, fmt.Errorf("nil value for key Asn")
	}

	return map[string]interface{}{
		"asn": *t.Asn,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Operator) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Operator"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Operator) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample represents the /sample/sample YANG schema element.
type Sample_Sample struct {
	ContainerVal	*Sample_Sample_ContainerVal	`path:"container-val"`
	EmptyVal	YANGEmpty	`path:"empty-val"`
	MultipleKeyList	map[Sample_Sample_MultipleKeyList_Key]*Sample_Sample_MultipleKeyList	`path:"multiple-key-list"`
	SingleKeyList	map[string]*Sample_Sample_SingleKeyList	`path:"single-key-list"`
	StrVal	*string	`path:"str-val"`
}

// IsYANGGoStruct ensures that Sample_Sample implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample) IsYANGGoStruct() {}

// Sample_Sample_MultipleKeyList_Key represents the key for list MultipleKeyList of element /sample/sample.
type Sample_Sample_MultipleKeyList_Key struct {
	Str	string	`path:"str"`
	Integer	uint32	`path:"integer"`
}

// NewMultipleKeyList creates a new entry in the MultipleKeyList list of the
// Sample_Sample struct. The keys of the list are populated from the input
// arguments.
func (t *Sample_Sample) NewMultipleKeyList(Str string, Integer uint32) (*Sample_Sample_MultipleKeyList, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.MultipleKeyList == nil {
		t.MultipleKeyList = make(map[Sample_Sample_MultipleKeyList_Key]*Sample_Sample_MultipleKeyList)
	}

	key := Sample_Sample_MultipleKeyList_Key{
		Str: Str,
		Integer: Integer,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.MultipleKeyList[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list MultipleKeyList", key)
	}

	t.MultipleKeyList[key] = &Sample_Sample_MultipleKeyList{
		Str: &Str,
		Integer: &Integer,
	}

	return t.MultipleKeyList[key], nil
}

// NewSingleKeyList creates a new entry in the SingleKeyList list of the
// Sample_Sample struct. The keys of the list are populated from the input
// arguments.
func (t *Sample_Sample) NewSingleKeyList(ListKey string) (*Sample_Sample_SingleKeyList, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.SingleKeyList == nil {
		t.SingleKeyList = make(map[string]*Sample_Sample_SingleKeyList)
	}

	key := ListKey

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.SingleKeyList[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list SingleKeyList", key)
	}

	t.SingleKeyList[key] = &Sample_Sample_SingleKeyList{
		ListKey: &ListKey,
	}

	return t.SingleKeyList[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample_ContainerVal represents the /sample/sample/container-val YANG schema element.
type Sample_Sample_ContainerVal struct {
	EnumVal	E_Sample_Sample_ContainerVal_EnumVal	`path:"enum-val"`
	LeafListV2	[]int32	`path:"leaf-list-v2"`
	LeafListVal	[]string	`path:"leaf-list-val"`
}

// IsYANGGoStruct ensures that Sample_Sample_ContainerVal implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_ContainerVal) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_ContainerVal) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_ContainerVal"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_ContainerVal) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample_MultipleKeyList represents the /sample/sample/multiple-key-list YANG schema element.
type Sample_Sample_MultipleKeyList struct {
	Integer	*uint32	`path:"integer"`
	Ok	*bool	`path:"ok"`
	Str	*string	`path:"str"`
}

// IsYANGGoStruct ensures that Sample_Sample_MultipleKeyList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_MultipleKeyList) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Sample_Sample_MultipleKeyList struct, which is a YANG list entry.
func (t *Sample_Sample_MultipleKeyList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Integer == nil {
		return nil, fmt.Errorf("nil value for key Integer")
	}

	if t.Str == nil {
		return nil, fmt.Errorf("nil value for key Str")
	}

	return map[string]interface{}{
		"integer": *t.Integer,
		"str": *t.Str,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_MultipleKeyList) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_MultipleKeyList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_MultipleKeyList) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Sample_Sample_SingleKeyList represents the /sample/sample/single-key-list YANG schema element.
type Sample_Sample_SingleKeyList struct {
	CountryCode	*string	`path:"country-code"`
	DialCode	*uint32	`path:"dial-code"`
	ListKey	*string	`path:"list-key"`
}

// IsYANGGoStruct ensures that Sample_Sample_SingleKeyList implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Sample_Sample_SingleKeyList) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Sample_Sample_SingleKeyList struct, which is a YANG list entry.
func (t *Sample_Sample_SingleKeyList) ΛListKeyMap() (map[string]interface{}, error) {
	if t.ListKey == nil {
		return nil, fmt.Errorf("nil value for key ListKey")
	}

	return map[string]interface{}{
		"list-key": *t.ListKey,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Sample_Sample_SingleKeyList) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Sample_Sample_SingleKeyList"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Sample_Sample_SingleKeyList) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_Network_Company_Enumval is a derived int64 type which is used to represent
// the enumerated node Network_Company_Enumval. An additional value named
// Network_Company_Enumval_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Network_Company_Enumval int64

// IsYANGGoEnum ensures that Network_Company_Enumval implements the yang.GoEnum
// interface. This ensures that Network_Company_Enumval can be identified as a
// mapped type for a YANG enumeration.
func (E_Network_Company_Enumval) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Network_Company_Enumval.
func (E_Network_Company_Enumval) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Network_Company_Enumval.
func (e E_Network_Company_Enumval) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Network_Company_Enumval")
}

const (
	// Network_Company_Enumval_UNSET corresponds to the value UNSET of Network_Company_Enumval
	Network_Company_Enumval_UNSET E_Network_Company_Enumval = 0
	// Network_Company_Enumval_enum1 corresponds to the value enum1 of Network_Company_Enumval
	Network_Company_Enumval_enum1 E_Network_Company_Enumval = 1
	// Network_Company_Enumval_enum2 corresponds to the value enum2 of Network_Company_Enumval
	Network_Company_Enumval_enum2 E_Network_Company_Enumval = 2
	// Network_Company_Enumval_enum3 corresponds to the value enum3 of Network_Company_Enumval
	Network_Company_Enumval_enum3 E_Network_Company_Enumval = 31
)


// E_Sample_Sample_ContainerVal_EnumVal is a derived int64 type which is used to represent
// the enumerated node Sample_Sample_ContainerVal_EnumVal. An additional value named
// Sample_Sample_ContainerVal_EnumVal_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Sample_Sample_ContainerVal_EnumVal int64

// IsYANGGoEnum ensures that Sample_Sample_ContainerVal_EnumVal implements the yang.GoEnum
// interface. This ensures that Sample_Sample_ContainerVal_EnumVal can be identified as a
// mapped type for a YANG enumeration.
func (E_Sample_Sample_ContainerVal_EnumVal) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Sample_Sample_ContainerVal_EnumVal.
func (E_Sample_Sample_ContainerVal_EnumVal) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Sample_Sample_ContainerVal_EnumVal.
func (e E_Sample_Sample_ContainerVal_EnumVal) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Sample_Sample_ContainerVal_EnumVal")
}

const (
	// Sample_Sample_ContainerVal_EnumVal_UNSET corresponds to the value UNSET of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_UNSET E_Sample_Sample_ContainerVal_EnumVal = 0
	// Sample_Sample_ContainerVal_EnumVal_enum1 corresponds to the value enum1 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum1 E_Sample_Sample_ContainerVal_EnumVal = 1
	// Sample_Sample_ContainerVal_EnumVal_enum2 corresponds to the value enum2 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum2 E_Sample_Sample_ContainerVal_EnumVal = 2
	// Sample_Sample_ContainerVal_EnumVal_enum3 corresponds to the value enum3 of Sample_Sample_ContainerVal_EnumVal
	Sample_Sample_ContainerVal_EnumVal_enum3 E_Sample_Sample_ContainerVal_EnumVal = 31
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Network_Company_Enumval": {
		1: {Name: "enum1"},
		2: {Name: "enum2"},
		31: {Name: "enum3"},
	},
	"E_Sample_Sample_ContainerVal_EnumVal": {
		1: {Name: "enum1"},
		2: {Name: "enum2"},
		31: {Name: "enum3"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5d, 0x5b, 0x6f, 0x9b, 0x48,
		0x14, 0x7e, 0xf7, 0xaf, 0x40, 0x3c, 0xc7, 0xaa, 0x2f, 0x24, 0x4e, 0xfc, 0xd6, 0x4d, 0x5a, 0xad,
		0x94, 0xa6, 0x5d, 0x35, 0xab, 0xbe, 0xac, 0xaa, 0x6a, 0xd6, 0x9e, 0xb8, 0x23, 0xc3, 0x80, 0x86,
		0x21, 0x8d, 0xb5, 0xf2, 0x7f, 0x5f, 0xd9, 0x80, 0x63, 0xcc, 0x5c, 0xce, 0x80, 0xbd, 0x6b, 0xc7,
		0xe7, 0xc9, 0x0a, 0x9c, 0x81, 0x33, 0x73, 0x6e, 0xdf, 0xf9, 0x18, 0xc8, 0x3f, 0x1d, 0xcf, 0xf3,
		0x3c, 0xff, 0x33, 0x89, 0xa8, 0x3f, 0xf6, 0xfc, 0x29, 0x7d, 0x66, 0x13, 0xea, 0x5f, 0xe4, 0x47,
		0xef, 0x19, 0x9f, 0xfa, 0x63, 0xaf, 0x5f, 0xfc, 0x79, 0x1b, 0xf3, 0x27, 0x36, 0xf3, 0xc7, 0x5e,
		0xaf, 0x38, 0x70, 0xc7, 0x84, 0x3f, 0xf6, 0xf2, 0x4b, 0xac, 0x0f, 0x4c, 0xe2, 0x28, 0x21, 0x7c,
		0x51, 0x39, 0x58, 0xb9, 0x7e, 0x29, 0x70, 0x51, 0x3d, 0x5d, 0xbd, 0xd1, 0xe6, 0xf0, 0xee, 0x0d,
		0x37, 0x27, 0xfe, 0x10, 0xf4, 0x89, 0xbd, 0xd4, 0x6e, 0x53, 0xb9, 0x15, 0xa7, 0x72, 0xe7, 0x36,
		0xeb, 0xd3, 0x8f, 0x71, 0x26, 0x26, 0x54, 0x39, 0x34, 0x57, 0x85, 0x2e, 0x7e, 0xc5, 0x62, 0xa5,
		0x8d, 0x9f, 0xe4, 0x77, 0xb9, 0x50, 0x0b, 0xfe, 0x4e, 0xd2, 0xf7, 0x62, 0x96, 0x45, 0x94, 0x4b,
		0x7f, 0xec, 0x49, 0x91, 0x51, 0x8d, 0xe0, 0x96, 0xd4, 0x5a, 0xa9, 0x9a, 0xd4, 0xb2, 0x72, 0x64,
		0xb9, 0x33, 0xd7, 0xdd, 0x45, 0xde, 0x9c, 0x20, 0xd3, 0xa9, 0xa0, 0x69, 0xaa, 0x9f, 0x4a, 0xb9,
		0x12, 0xa5, 0xa0, 0x46, 0xbf, 0x62, 0xf1, 0x7b, 0x9a, 0xd3, 0x3a, 0x23, 0x40, 0x8c, 0x01, 0x34,
		0x0a, 0xd4, 0x38, 0xce, 0x46, 0x72, 0x36, 0x16, 0xdc, 0x68, 0x6a, 0xe3, 0x69, 0x8c, 0xb8, 0xb9,
		0xec, 0x9f, 0x8b, 0x84, 0xc2, 0x56, 0x2a, 0x95, 0x82, 0xf1, 0x99, 0x69, 0xb1, 0xca, 0xa0, 0xb9,
		0x76, 0xd2, 0xe0, 0x13, 0x4b, 0xe5, 0x7b, 0x29, 0x85, 0x59, 0x8b, 0x07, 0xc6, 0x3f, 0x84, 0x74,
		0xb5, 0x00, 0xa9, 0xde, 0xf2, 0xb9, 0x24, 0x79, 0xd9, 0x92, 0xec, 0x5f, 0x07, 0xc1, 0xd5, 0x28,
		0x08, 0x7a, 0xa3, 0xe1, 0xa8, 0x77, 0x73, 0x79, 0xd9, 0xbf, 0xea, 0x5f, 0x1a, 0x06, 0x7f, 0x11,
		0x53, 0x2a, 0xe8, 0xf4, 0xb7, 0x55, 0xc6, 0xe0, 0x59, 0x18, 0x76, 0x60, 0x2b, 0xac, 0x98, 0x9b,
		0x4f, 0x79, 0x16, 0x3d, 0x93, 0xd0, 0x1e, 0x0d, 0xa5, 0x20, 0x46, 0xc3, 0x09, 0x45, 0xc3, 0xca,
		0x68, 0x54, 0x10, 0xc9, 0x62, 0x0e, 0x09, 0x89, 0xc0, 0x20, 0xf3, 0x81, 0x67, 0xd1, 0xea, 0xa6,
		0xcb, 0x16, 0xce, 0xc6, 0x73, 0xb5, 0x2c, 0x9e, 0xb6, 0x96, 0x42, 0x37, 0x3b, 0xa7, 0xa4, 0xeb,
		0x58, 0xdb, 0xdf, 0x73, 0x1e, 0xcb, 0xdc, 0xab, 0x95, 0x25, 0x3e, 0x9d, 0xfc, 0xa4, 0x11, 0x49,
		0x88, 0xfc, 0xb9, 0xd2, 0xee, 0x1d, 0xa7, 0xf2, 0x57, 0x2c, 0xe6, 0xef, 0xd4, 0x28, 0x2a, 0x1f,
		0x21, 0x45, 0x36, 0x91, 0x85, 0x7f, 0xfa, 0x9f, 0xf3, 0x01, 0x3f, 0x6e, 0x8b, 0x01, 0x1d, 0xb5,
		0x6a, 0x5b, 0x6a, 0xf9, 0x93, 0x38, 0xe3, 0x52, 0x18, 0x21, 0x5c, 0x2e, 0x80, 0x10, 0xae, 0x3d,
		0x84, 0x2b, 0xd6, 0xb2, 0x3b, 0x89, 0xa7, 0x80, 0x7c, 0x52, 0x91, 0xc6, 0xbc, 0x72, 0xde, 0x79,
		0x45, 0x11, 0x17, 0x53, 0x46, 0x42, 0xa0, 0x2b, 0xbd, 0x8a, 0xa2, 0x1f, 0x9d, 0x90, 0x1f, 0x65,
		0x8c, 0xcb, 0xe1, 0x00, 0xe0, 0x47, 0x23, 0x83, 0xc8, 0x57, 0xc2, 0x67, 0xab, 0xab, 0xfd, 0x65,
		0x9c, 0xac, 0x79, 0xb1, 0xcb, 0x26, 0xc1, 0x6a, 0x15, 0xa0, 0x43, 0xd5, 0xc4, 0xbf, 0x91, 0x30,
		0xa3, 0xf5, 0x7a, 0xa2, 0x95, 0xff, 0x28, 0xc8, 0x64, 0x55, 0x47, 0xef, 0xd8, 0x8c, 0xe5, 0x3d,
		0x8b, 0x75, 0xdc, 0xf2, 0x02, 0x30, 0x45, 0xf2, 0x72, 0xf0, 0x29, 0x06, 0x37, 0x83, 0x03, 0x4e,
		0xb2, 0xd3, 0xec, 0xec, 0x77, 0x44, 0xc7, 0x98, 0x7d, 0xfe, 0x67, 0x74, 0x7c, 0x4f, 0x17, 0x1a,
		0x47, 0x31, 0xb3, 0x18, 0x76, 0xf6, 0xa2, 0x11, 0x6b, 0x61, 0x66, 0x2b, 0xf6, 0x06, 0xed, 0x55,
		0xe8, 0xda, 0x08, 0xed, 0xf3, 0x01, 0x00, 0x68, 0x1f, 0x11, 0x21, 0x18, 0x9d, 0xea, 0xa1, 0x7d,
		0x29, 0xa0, 0x86, 0xf6, 0x3d, 0x84, 0xf6, 0x75, 0x33, 0x6b, 0xa3, 0xe7, 0x95, 0xba, 0x88, 0x12,
		0xa9, 0xb4, 0x67, 0x19, 0x2c, 0x43, 0x88, 0xe9, 0xb2, 0x50, 0xb2, 0x39, 0x5d, 0x84, 0x2c, 0x95,
		0x06, 0xfb, 0x6d, 0x4b, 0x61, 0x7f, 0xd6, 0xbe, 0x3f, 0x63, 0x5c, 0xd2, 0x19, 0x15, 0xf6, 0x62,
		0x56, 0x0a, 0x62, 0x3d, 0x43, 0x34, 0x7d, 0xc4, 0x68, 0xba, 0x77, 0x06, 0x68, 0x7a, 0x70, 0x13,
		0xdc, 0x5c, 0x8d, 0x06, 0x37, 0x97, 0x6f, 0x0b, 0x54, 0xc7, 0x73, 0x7b, 0x16, 0x8a, 0xe7, 0x98,
		0x80, 0x4e, 0x29, 0x01, 0xfd, 0x1d, 0xc7, 0x21, 0x25, 0xa0, 0x27, 0x1a, 0xfd, 0x16, 0xae, 0x93,
		0x4a, 0x40, 0x05, 0x5b, 0x09, 0xa1, 0xf3, 0x60, 0x37, 0x66, 0xeb, 0xc6, 0x52, 0x29, 0x3c, 0x35,
		0xda, 0x79, 0xbb, 0x4d, 0x99, 0x01, 0x57, 0x1b, 0x3a, 0xb3, 0x87, 0xed, 0x51, 0x00, 0x8c, 0x1f,
		0x27, 0x54, 0x10, 0x19, 0x0b, 0x3d, 0xbe, 0xdf, 0x48, 0x20, 0xb6, 0x6f, 0x8f, 0xed, 0x49, 0xca,
		0x01, 0x5b, 0x67, 0x52, 0x8e, 0x59, 0x11, 0x31, 0x3d, 0x62, 0x7a, 0xc4, 0xf4, 0x48, 0x94, 0x63,
		0x12, 0x3a, 0x6e, 0x68, 0x56, 0x2f, 0x56, 0x6f, 0x17, 0x92, 0x69, 0xa0, 0x90, 0x01, 0x8e, 0x7d,
		0x29, 0x47, 0x00, 0xa0, 0x58, 0x42, 0x45, 0xaa, 0x50, 0x68, 0x63, 0xe0, 0xe2, 0x3c, 0xf2, 0xe4,
		0x7b, 0xe4, 0xc9, 0xb5, 0x41, 0xa3, 0x09, 0x16, 0xb5, 0xe5, 0x52, 0x12, 0x25, 0x21, 0xd5, 0x5b,
		0xae, 0x38, 0x8f, 0x00, 0xba, 0x3d, 0x80, 0x9e, 0xc4, 0x5c, 0x12, 0xc6, 0xa9, 0xe8, 0x82, 0xf6,
		0xdd, 0x56, 0xc5, 0xcd, 0xf5, 0xac, 0x8f, 0xf5, 0xec, 0xf0, 0xf5, 0x4c, 0x67, 0xd8, 0x8d, 0x00,
		0xe5, 0x59, 0x64, 0xb4, 0x6d, 0xfd, 0x59, 0x57, 0x39, 0xc2, 0x32, 0x23, 0x18, 0x0e, 0xb4, 0x9a,
		0xdb, 0xc5, 0xec, 0x8e, 0xe6, 0x77, 0x75, 0x83, 0xc6, 0xee, 0xd0, 0xd8, 0x2d, 0xdc, 0xdd, 0x03,
		0x08, 0x75, 0x2d, 0x6b, 0x6d, 0x85, 0x41, 0x4a, 0xaf, 0xb0, 0x6f, 0xde, 0xae, 0xe5, 0x80, 0x00,
		0x20, 0x6b, 0xde, 0xcc, 0x6d, 0x9f, 0xb0, 0x61, 0xb2, 0x7e, 0x48, 0xc9, 0x53, 0x37, 0x64, 0xa9,
		0xec, 0x3e, 0x0f, 0xe0, 0x21, 0x50, 0x19, 0x85, 0x61, 0x80, 0x61, 0xb0, 0xfd, 0x8c, 0x78, 0x38,
		0x70, 0x08, 0x80, 0x21, 0x40, 0x14, 0xc6, 0x54, 0xc0, 0x19, 0x8b, 0x46, 0xcc, 0x05, 0xb0, 0x7a,
		0x5b, 0xdb, 0xfc, 0x41, 0x3f, 0x18, 0x05, 0xd7, 0xc3, 0xab, 0xe0, 0xda, 0xf1, 0x02, 0x0d, 0xda,
		0x7d, 0x07, 0x8a, 0xa3, 0x11, 0xd5, 0xd1, 0x90, 0xf2, 0xd0, 0xaf, 0xc9, 0xe8, 0x3f, 0x5c, 0x93,
		0xce, 0x7e, 0xa4, 0xbe, 0xb7, 0x0a, 0x30, 0xd0, 0x8b, 0x6a, 0xf0, 0x56, 0x76, 0x2f, 0xad, 0xad,
		0x5b, 0xab, 0xbb, 0xf7, 0x32, 0xe4, 0x02, 0xc5, 0xaa, 0xc3, 0xb0, 0x10, 0x61, 0x21, 0x82, 0xd3,
		0x53, 0x40, 0x9a, 0x0a, 0x23, 0xb9, 0x6d, 0x0b, 0x66, 0x21, 0xbf, 0x74, 0x24, 0x58, 0x4e, 0x62,
		0x94, 0x3f, 0x90, 0xc6, 0x5a, 0xc1, 0x8b, 0x3d, 0xae, 0x47, 0xff, 0x28, 0x7e, 0x6e, 0xcb, 0x8b,
		0x7c, 0x23, 0xa1, 0xdf, 0xe6, 0x35, 0xdc, 0x28, 0x91, 0x0b, 0x18, 0x21, 0xf0, 0x2a, 0x8a, 0xe4,
		0xf6, 0x29, 0xbd, 0x8a, 0xab, 0xd9, 0xcf, 0x5a, 0x4b, 0x1a, 0xc3, 0x16, 0x6e, 0xb4, 0x7e, 0xe2,
		0x9e, 0x84, 0xb4, 0x3b, 0xa7, 0x8b, 0xae, 0x72, 0xd3, 0x6b, 0x4d, 0xaf, 0xfa, 0x10, 0xe4, 0x98,
		0x8e, 0x9f, 0x63, 0xb2, 0xed, 0xb0, 0x55, 0x75, 0x51, 0x86, 0x9d, 0xb6, 0x88, 0x68, 0xce, 0x12,
		0xd1, 0x64, 0xae, 0xbd, 0xf5, 0xe8, 0x54, 0x7b, 0xeb, 0xa6, 0x7d, 0x64, 0x0f, 0x5b, 0xea, 0xa6,
		0xbb, 0x09, 0x4e, 0xa8, 0xa5, 0x6e, 0xd4, 0x60, 0x1a, 0x76, 0x16, 0xd7, 0x02, 0x4d, 0xbb, 0xc3,
		0x18, 0x13, 0xef, 0x59, 0x26, 0x5e, 0xfb, 0x0e, 0xe6, 0x1a, 0xec, 0xea, 0x1f, 0xc0, 0x85, 0x53,
		0xe9, 0x80, 0x20, 0xf4, 0x3b, 0x9d, 0xd1, 0x89, 0x91, 0x0f, 0xd9, 0x07, 0x1f, 0xb2, 0x27, 0xf0,
		0x6c, 0xdd, 0x71, 0xed, 0xc6, 0xb0, 0x1c, 0xd7, 0x47, 0xbd, 0x0e, 0xc9, 0x88, 0x40, 0x5b, 0x41,
		0x2b, 0x2b, 0xf2, 0x50, 0x5c, 0xe8, 0x9e, 0x2e, 0x3e, 0xd5, 0x76, 0x71, 0xbb, 0x75, 0xb4, 0x29,
		0xe3, 0x33, 0xa7, 0x7e, 0x76, 0x77, 0x00, 0x76, 0xb3, 0xc7, 0xdf, 0xcd, 0x82, 0xbe, 0xe7, 0x53,
		0x5b, 0x56, 0xc0, 0x77, 0x7d, 0xb0, 0x32, 0x61, 0x65, 0x3a, 0x6c, 0x65, 0x32, 0xc4, 0xb5, 0xfd,
		0xbb, 0x42, 0x35, 0xc5, 0x6d, 0xdf, 0x17, 0x42, 0x7f, 0x46, 0x9e, 0x06, 0x79, 0x1a, 0x05, 0x39,
		0xd1, 0x47, 0x9e, 0xc6, 0xf9, 0xbb, 0x48, 0x6f, 0x9d, 0xa0, 0x59, 0x3f, 0xc5, 0x9f, 0xd3, 0x85,
		0xc3, 0xc3, 0xff, 0x72, 0x04, 0x66, 0x5f, 0xcc, 0xbe, 0xa7, 0xd2, 0xe7, 0x5a, 0x9c, 0x16, 0x9b,
		0xdc, 0x6a, 0x93, 0x0b, 0xeb, 0x0f, 0xad, 0x2d, 0xee, 0xe3, 0xfa, 0x32, 0xfb, 0x68, 0x70, 0x25,
		0xf0, 0x45, 0x80, 0x52, 0x10, 0x9f, 0xfa, 0xe3, 0x2b, 0x6d, 0x3a, 0x0d, 0x5d, 0x5f, 0x0b, 0xab,
		0x84, 0x86, 0xfd, 0x9d, 0xb0, 0x4a, 0x08, 0x68, 0x5f, 0x08, 0xeb, 0x6c, 0x29, 0xa6, 0x53, 0xc8,
		0x67, 0xe9, 0x47, 0x32, 0xa7, 0x5f, 0xe3, 0xb8, 0x6e, 0xc9, 0x5d, 0x25, 0xfd, 0xed, 0x53, 0x15,
		0x7d, 0xee, 0xf2, 0x7f, 0xbb, 0x91, 0xdf, 0xb0, 0xb3, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x01,
		0x00, 0x00, 0xff, 0xff, 0xdf, 0xfe, 0x69, 0xbf, 0x95, 0x63, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/company/enumval": []reflect.Type{
		reflect.TypeOf((E_Network_Company_Enumval)(0)),
	},
	"/sample/container-val/enum-val": []reflect.Type{
		reflect.TypeOf((E_Sample_Sample_ContainerVal_EnumVal)(0)),
	},
}

