/*
Package schema is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/neoul/go/src/github.com/openconfig/ygot/genutil/names.go
using the following YANG input files:
	- ../yang/example.yang
Imported modules were sourced from:
	- yang/...
*/
package schema

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
	gpb "github.com/openconfig/gnmi/proto/gnmi"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}
// ΓModelData contains the catalogue information corresponding to the modules for
// which Go code was generated.
var ΓModelData = []*gpb.ModelData{
    {
		Name: "network",
		Organization: "Actus Networks",
	},
}

// Device represents the /device YANG schema element.
type Device struct {
	Company	*Network_Company	`path:"company" module:"network"`
	Country	map[string]*Network_Country	`path:"country" module:"network"`
	Married	YANGEmpty	`path:"married" module:"network"`
	Operator	map[uint32]*Network_Operator	`path:"operator" module:"network"`
	Person	*string	`path:"person" module:"network"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// NewCountry creates a new entry in the Country list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewCountry(Name string) (*Network_Country, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Country == nil {
		t.Country = make(map[string]*Network_Country)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Country[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Country", key)
	}

	t.Country[key] = &Network_Country{
		Name: &Name,
	}

	return t.Country[key], nil
}

// NewOperator creates a new entry in the Operator list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewOperator(Asn uint32) (*Network_Operator, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Operator == nil {
		t.Operator = make(map[uint32]*Network_Operator)
	}

	key := Asn

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Operator[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Operator", key)
	}

	t.Operator[key] = &Network_Operator{
		Asn: &Asn,
	}

	return t.Operator[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Company represents the /network/company YANG schema element.
type Network_Company struct {
	Address	[]string	`path:"address" module:"network"`
	Enumval	E_Network_Company_Enumval	`path:"enumval" module:"network"`
	Name	*string	`path:"name" module:"network"`
}

// IsYANGGoStruct ensures that Network_Company implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Company) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Company) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Company"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Company) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Country represents the /network/country YANG schema element.
type Network_Country struct {
	CountryCode	*string	`path:"country-code" module:"network"`
	DialCode	*uint32	`path:"dial-code" module:"network"`
	Name	*string	`path:"name" module:"network"`
}

// IsYANGGoStruct ensures that Network_Country implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Country) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Country struct, which is a YANG list entry.
func (t *Network_Country) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Country) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Country"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Country) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Network_Operator represents the /network/operator YANG schema element.
type Network_Operator struct {
	Asn	*uint32	`path:"asn" module:"network"`
	Name	*string	`path:"name" module:"network"`
}

// IsYANGGoStruct ensures that Network_Operator implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Network_Operator) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Network_Operator struct, which is a YANG list entry.
func (t *Network_Operator) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Asn == nil {
		return nil, fmt.Errorf("nil value for key Asn")
	}

	return map[string]interface{}{
		"asn": *t.Asn,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Network_Operator) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Network_Operator"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Network_Operator) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_Network_Company_Enumval is a derived int64 type which is used to represent
// the enumerated node Network_Company_Enumval. An additional value named
// Network_Company_Enumval_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_Network_Company_Enumval int64

// IsYANGGoEnum ensures that Network_Company_Enumval implements the yang.GoEnum
// interface. This ensures that Network_Company_Enumval can be identified as a
// mapped type for a YANG enumeration.
func (E_Network_Company_Enumval) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  Network_Company_Enumval.
func (E_Network_Company_Enumval) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_Network_Company_Enumval.
func (e E_Network_Company_Enumval) String() string {
	return ygot.EnumLogString(e, int64(e), "E_Network_Company_Enumval")
}

const (
	// Network_Company_Enumval_UNSET corresponds to the value UNSET of Network_Company_Enumval
	Network_Company_Enumval_UNSET E_Network_Company_Enumval = 0
	// Network_Company_Enumval_enum1 corresponds to the value enum1 of Network_Company_Enumval
	Network_Company_Enumval_enum1 E_Network_Company_Enumval = 1
	// Network_Company_Enumval_enum2 corresponds to the value enum2 of Network_Company_Enumval
	Network_Company_Enumval_enum2 E_Network_Company_Enumval = 2
	// Network_Company_Enumval_enum3 corresponds to the value enum3 of Network_Company_Enumval
	Network_Company_Enumval_enum3 E_Network_Company_Enumval = 31
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_Network_Company_Enumval": {
		1: {Name: "enum1"},
		2: {Name: "enum2"},
		31: {Name: "enum3"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5a, 0x5f, 0x6f, 0xda, 0x3e,
		0x14, 0x7d, 0xcf, 0xa7, 0x88, 0xfc, 0xcc, 0x4f, 0xe5, 0x47, 0xd9, 0x3a, 0x78, 0x63, 0xa5, 0xd5,
		0xa4, 0xae, 0xed, 0xd4, 0x4d, 0x7b, 0x99, 0xa6, 0xc9, 0x4a, 0x6e, 0xa9, 0xd5, 0xc4, 0x8e, 0x6e,
		0x9c, 0x16, 0x34, 0xf1, 0xdd, 0xa7, 0xe0, 0x24, 0x25, 0xc4, 0x36, 0x66, 0xa5, 0xda, 0x3a, 0xfc,
		0x88, 0x7d, 0xec, 0xfb, 0xe7, 0xdc, 0x6b, 0x9f, 0x58, 0xfc, 0x0c, 0xc2, 0x30, 0x0c, 0xc9, 0x15,
		0x4d, 0x81, 0x8c, 0x43, 0x12, 0xc3, 0x03, 0x8b, 0x80, 0xf4, 0xd4, 0xe8, 0x05, 0xe3, 0x31, 0x19,
		0x87, 0xff, 0x57, 0x3f, 0x4f, 0x05, 0xbf, 0x65, 0x33, 0x32, 0x0e, 0xfb, 0xd5, 0xc0, 0x94, 0x21,
		0x19, 0x87, 0x6a, 0x8b, 0xd5, 0x40, 0x24, 0xd2, 0x8c, 0xf2, 0x45, 0x6b, 0xb0, 0xb5, 0x7f, 0x0d,
		0xe8, 0xb5, 0xa7, 0xdb, 0x86, 0x9a, 0xe1, 0x4d, 0x83, 0xcd, 0xc4, 0x27, 0x84, 0x5b, 0x36, 0xef,
		0x98, 0x69, 0x99, 0xe2, 0x20, 0x37, 0xcc, 0xac, 0xa6, 0x3f, 0x8b, 0x02, 0x23, 0xd0, 0x2e, 0x55,
		0xae, 0xc0, 0xe2, 0x51, 0x60, 0xe9, 0x0d, 0xc9, 0x94, 0x95, 0x9e, 0x1e, 0xf8, 0x81, 0xe6, 0x13,
		0x9c, 0x15, 0x29, 0x70, 0x49, 0xc6, 0xa1, 0xc4, 0x02, 0x0c, 0xc0, 0x35, 0xd4, 0xca, 0xa9, 0x0e,
		0x6a, 0xd9, 0x1a, 0x59, 0x6e, 0xc4, 0xba, 0x99, 0xe4, 0x66, 0x82, 0xc6, 0x31, 0x42, 0x9e, 0x9b,
		0x43, 0xa9, 0x33, 0x51, 0x03, 0x0d, 0xfe, 0x55, 0xc9, 0xef, 0x1b, 0xa6, 0x4d, 0x24, 0xb8, 0x90,
		0xe1, 0x48, 0x8a, 0x2b, 0x39, 0x3b, 0x93, 0xb4, 0x33, 0x59, 0xee, 0xa4, 0xe9, 0xc9, 0x33, 0x90,
		0xd8, 0x6c, 0xfb, 0x65, 0x91, 0x81, 0x5b, 0xa6, 0x72, 0x89, 0x8c, 0xcf, 0x6c, 0xc9, 0xaa, 0x9b,
		0xe6, 0xdd, 0x4e, 0x1e, 0x7c, 0x64, 0xb9, 0x9c, 0x48, 0x89, 0x76, 0x2f, 0x2e, 0x19, 0x3f, 0x4b,
		0xa0, 0x4c, 0x40, 0x59, 0x5f, 0xbc, 0x48, 0x12, 0x8b, 0x23, 0x97, 0x74, 0xee, 0x0e, 0xbe, 0xc6,
		0x18, 0x10, 0xe2, 0xf7, 0x8b, 0x0a, 0x1a, 0xb8, 0x25, 0x55, 0x13, 0x0e, 0x01, 0x5e, 0xa4, 0x0f,
		0x34, 0xd9, 0xde, 0x00, 0x35, 0xd0, 0x37, 0xc0, 0x2b, 0x6a, 0x80, 0x92, 0x34, 0x40, 0x2a, 0x99,
		0xe0, 0x2e, 0x5d, 0x30, 0xb4, 0x60, 0xce, 0x78, 0x91, 0x96, 0x46, 0x97, 0xcf, 0x28, 0x36, 0xae,
		0xdc, 0xda, 0x52, 0x69, 0x2b, 0x94, 0x2f, 0xb3, 0x43, 0x3a, 0x67, 0x77, 0xbc, 0xce, 0x27, 0x9c,
		0x0b, 0xa9, 0xaa, 0x5a, 0x7b, 0xab, 0xe7, 0xd1, 0x1d, 0xa4, 0x34, 0xa3, 0xf2, 0xae, 0xf4, 0xee,
		0x88, 0x83, 0x7c, 0x14, 0x78, 0x7f, 0xa4, 0x17, 0x4e, 0x6a, 0x85, 0xc4, 0x22, 0x92, 0x55, 0x7d,
		0x92, 0x2b, 0xb5, 0xe0, 0xc7, 0x69, 0xb5, 0x20, 0xd0, 0xbb, 0xb6, 0xe6, 0x16, 0x89, 0x44, 0xc1,
		0x25, 0x5a, 0x55, 0x9b, 0x02, 0x78, 0xd5, 0xf6, 0x7c, 0xd5, 0x56, 0xe5, 0xf2, 0xbf, 0x48, 0xc4,
		0x0e, 0xe7, 0x49, 0x0b, 0xed, 0xcf, 0x95, 0xc3, 0x3e, 0x57, 0x34, 0x7d, 0x11, 0x33, 0x9a, 0x38,
		0x96, 0xd2, 0x13, 0xd4, 0xd7, 0xd1, 0x2b, 0xaa, 0xa3, 0x82, 0x71, 0x79, 0x3c, 0x70, 0xa8, 0xa3,
		0x13, 0x0b, 0xe4, 0x86, 0xf2, 0x59, 0xb9, 0xdb, 0x37, 0x6b, 0xb0, 0xf6, 0x64, 0xd7, 0xdf, 0x05,
		0x5b, 0x59, 0x71, 0x2c, 0xa8, 0x0e, 0xfc, 0x2b, 0x4d, 0x0a, 0xe8, 0xde, 0x27, 0x46, 0xfc, 0x39,
		0xd2, 0xa8, 0xbc, 0x47, 0xa7, 0x6c, 0xc6, 0x56, 0x5f, 0x1e, 0xfd, 0xad, 0xeb, 0x96, 0x3d, 0x87,
		0x10, 0xe9, 0xfc, 0xc5, 0x43, 0x1c, 0x8e, 0x06, 0x2f, 0x18, 0x64, 0xf0, 0x7b, 0xb3, 0xdf, 0xbd,
		0x3a, 0xf6, 0xa7, 0xcf, 0x1f, 0x56, 0xc7, 0x17, 0xb0, 0x30, 0x14, 0x8a, 0xfd, 0xe1, 0xc2, 0xe9,
		0xc1, 0xc2, 0xe9, 0xa1, 0xc2, 0xfe, 0x40, 0xb1, 0x37, 0x35, 0xaf, 0x13, 0xd4, 0x56, 0x35, 0xaf,
		0x16, 0x38, 0xa8, 0xf9, 0x94, 0x22, 0x32, 0x88, 0xcd, 0x6a, 0xbe, 0x06, 0xe8, 0xd5, 0x7c, 0xdf,
		0xab, 0xf9, 0x2e, 0xcd, 0xc6, 0x86, 0x79, 0x7a, 0xad, 0x48, 0x33, 0xa9, 0xe5, 0xb3, 0xee, 0x8f,
		0x63, 0x07, 0xea, 0x44, 0x06, 0x48, 0xa5, 0x40, 0x33, 0x77, 0x0d, 0xc2, 0x7f, 0x8a, 0xed, 0xe1,
		0x01, 0x3d, 0xe7, 0x0e, 0x8f, 0xe7, 0x39, 0xf7, 0x57, 0x96, 0x17, 0xcc, 0x7f, 0xb3, 0x60, 0xee,
		0x1f, 0x80, 0x60, 0x1e, 0x8c, 0x86, 0xa3, 0xb7, 0x27, 0x83, 0xd1, 0x1b, 0xaf, 0x9b, 0xfd, 0x21,
		0xe4, 0x75, 0xb3, 0x41, 0x37, 0x77, 0x2f, 0xab, 0x7f, 0x4a, 0x36, 0x1b, 0xd4, 0x8f, 0x45, 0x37,
		0x5f, 0xd7, 0x2b, 0x1c, 0xd4, 0x57, 0x06, 0x98, 0x6b, 0x1c, 0x6a, 0x38, 0xad, 0xe6, 0xbd, 0x6c,
		0xde, 0xa3, 0x6c, 0x36, 0xf6, 0x89, 0xa1, 0x3f, 0xd6, 0x98, 0x0b, 0xd6, 0x2c, 0x9a, 0x0a, 0x8a,
		0xb0, 0xfc, 0x9c, 0xde, 0xc3, 0x8d, 0x10, 0xdd, 0x40, 0x37, 0x8b, 0x8c, 0xac, 0x4f, 0xb5, 0x8a,
		0x69, 0xaa, 0xfe, 0x14, 0xa3, 0x0c, 0x06, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00,
		0x00, 0xff, 0xff, 0x2f, 0x7c, 0xd8, 0xef, 0x33, 0x23, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/company/enumval": []reflect.Type{
		reflect.TypeOf((E_Network_Company_Enumval)(0)),
	},
}

